import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { getActiveTenantWithPermission, getTenantPermissionSet } from "@/lib/tenant-context";
import { createInvitationToken, invitationExpiresAt } from "@/lib/team-invitations";
import { deliverTeamInvitation, findAuthUserByEmail } from "@/lib/team-invitation-delivery";
import { trialMutationError } from "@/lib/trials";

const baseMember = z.object({ membershipId: z.string().uuid() });
const schema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("invite"), firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().max(80), email: z.string().trim().email(), role: z.enum(["member","guest"]), personalMessage: z.string().trim().max(1000) }),
  baseMember.extend({ action: z.literal("profile"), lifecycleStage: z.enum(["lead","onboarding","active","at_risk","inactive","alumni"]), audienceSource: z.enum(["direct","invitation","signup","checkout","import","admin"]), preferredName: z.string().trim().max(120), jobTitle: z.string().trim().max(160), organization: z.string().trim().max(200), phone: z.string().trim().max(60), location: z.string().trim().max(200), timezone: z.string().trim().min(1).max(80), bio: z.string().trim().max(3000) }),
  baseMember.extend({ action: z.literal("status"), status: z.enum(["active","inactive","suspended"]) }),
  baseMember.extend({ action: z.literal("plan"), planId: z.string().uuid().nullable(), status: z.enum(["active","trialing","cancelled"]), assignmentType: z.enum(["manual","complimentary"]) }),
  baseMember.extend({ action: z.literal("segments"), tagIds: z.array(z.string().uuid()).max(50), groupIds: z.array(z.string().uuid()).max(50) }),
  baseMember.extend({ action: z.literal("note"), body: z.string().trim().min(1).max(5000) }),
  z.object({ action: z.literal("tag"), name: z.string().trim().min(1).max(80), color: z.string().regex(/^#[0-9a-fA-F]{6}$/), description: z.string().trim().max(500) })
]);

async function memberRecord(admin: ReturnType<typeof createAdminClient>, tenantId: string, membershipId: string) {
  const { data } = await admin.from("tenant_memberships").select("id,user_id,role,status").eq("id", membershipId).eq("tenant_id", tenantId).in("role", ["member","guest"]).maybeSingle(); return data;
}
async function audit(tenantId: string, userId: string, action: string, entityId?: string, metadata: Record<string, unknown> = {}) { await createAdminClient().from("audit_logs").insert({ tenant_id: tenantId, user_id: userId, action, entity_type: "tenant_membership", entity_id: entityId, metadata }); }

export async function GET() {
  const context = await getActiveTenantWithPermission("tenant.members.view"); if (!context) return NextResponse.json({ error: "Member directory permission is required." }, { status: 403 });
  const permissions = await getTenantPermissionSet(context.role); const canManage = permissions.has("tenant.members.manage"); const admin = createAdminClient();
  const [membershipResult, profileResult, subscriptionResult, planResult, tagResult, assignmentResult, groupResult, groupMemberResult, noteResult, invitationResult] = await Promise.all([
    admin.from("tenant_memberships").select("id,user_id,role,status,created_at,updated_at,joined_at,last_active_at,audience_source,lifecycle_stage").eq("tenant_id", context.tenant.id).in("role", ["member","guest"]).order("created_at", { ascending: false }),
    admin.from("tenant_member_profiles").select("*").eq("tenant_id", context.tenant.id),
    admin.from("member_subscriptions").select("id,user_id,plan_id,status,assignment_type,starts_at,renewal_at,current_period_end,updated_at").eq("tenant_id", context.tenant.id).order("updated_at", { ascending: false }),
    admin.from("tenant_membership_plans").select("id,name,status,plan_type").eq("tenant_id", context.tenant.id).order("sort_order"),
    admin.from("member_tags").select("*").eq("tenant_id", context.tenant.id).order("name"),
    admin.from("member_tag_assignments").select("membership_id,tag_id").eq("tenant_id", context.tenant.id),
    admin.from("groups").select("id,name,status").eq("tenant_id", context.tenant.id).order("name"),
    admin.from("group_members").select("group_id,user_id").eq("tenant_id", context.tenant.id),
    canManage ? admin.from("member_notes").select("id,membership_id,body,created_by,created_at").eq("tenant_id", context.tenant.id).order("created_at", { ascending: false }) : Promise.resolve({ data: [], error: null }),
    admin.from("tenant_invitations").select("id,email,first_name,last_name,role,status,expires_at,created_at").eq("tenant_id", context.tenant.id).in("role", ["member","guest"]).in("status", ["pending","sent","failed"]).order("created_at", { ascending: false })
  ]);
  const readError = membershipResult.error ?? profileResult.error ?? subscriptionResult.error ?? tagResult.error ?? assignmentResult.error ?? groupResult.error ?? groupMemberResult.error;
  if (readError) return NextResponse.json({ error: /audience_source|assignment_type|tenant_member_profiles|member_tags|schema cache/i.test(readError.message) ? "Member migration 0030 is required." : "Unable to load the member directory." }, { status: 500 });
  const memberships = membershipResult.data ?? []; const authResults = await Promise.all(memberships.map((membership) => admin.auth.admin.getUserById(membership.user_id))); const authUsers = Object.fromEntries(authResults.map((result) => result.data.user).filter(Boolean).map((user) => [user!.id, { email: user!.email, lastSignInAt: user!.last_sign_in_at, createdAt: user!.created_at, metadata: user!.user_metadata }]));
  return NextResponse.json({ tenant: context.tenant, canManage, memberships, profiles: profileResult.data ?? [], subscriptions: subscriptionResult.data ?? [], plans: planResult.data ?? [], tags: tagResult.data ?? [], tagAssignments: assignmentResult.data ?? [], groups: groupResult.data ?? [], groupMembers: groupMemberResult.data ?? [], notes: noteResult.data ?? [], invitations: invitationResult.data ?? [], authUsers });
}

export async function POST(request: NextRequest) {
  const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Check the member fields." }, { status: 400 });
  const context = await getActiveTenantWithPermission("tenant.members.manage"); if (!context) return NextResponse.json({ error: "Member management permission is required." }, { status: 403 });
  const admin = createAdminClient(); const input = parsed.data; const now = new Date().toISOString(); const trialError = await trialMutationError(context.tenant.id, input.action === "invite" ? "invitation" : "content"); if (trialError) return NextResponse.json({ error: trialError }, { status: 402 });
  if (input.action === "invite") {
    const email = input.email.toLowerCase(); const since = new Date(Date.now() - 3600000).toISOString(); const { count } = await admin.from("audit_logs").select("id", { count: "exact", head: true }).eq("tenant_id", context.tenant.id).eq("user_id", context.user.id).eq("action", "tenant.member.invitation_attempted").gte("created_at", since); if (Number(count ?? 0) >= 25) return NextResponse.json({ error: "Member invitation limit reached. Try again later." }, { status: 429 });
    const existingUser = await findAuthUserByEmail(email); if (existingUser) { const { data: existing } = await admin.from("tenant_memberships").select("id").eq("tenant_id", context.tenant.id).eq("user_id", existingUser.id).maybeSingle(); if (existing) return NextResponse.json({ error: "This person already belongs to the organization." }, { status: 409 }); }
    const { data: duplicate } = await admin.from("tenant_invitations").select("id").eq("tenant_id", context.tenant.id).eq("email", email).in("status", ["pending","sent"]).maybeSingle(); if (duplicate) return NextResponse.json({ error: "An active invitation already exists for this email." }, { status: 409 });
    const { token, tokenHash } = createInvitationToken(); const expiresAt = invitationExpiresAt(); const { data: invitation, error } = await admin.from("tenant_invitations").insert({ tenant_id: context.tenant.id, email, first_name: input.firstName, last_name: input.lastName, role: input.role, personal_message: input.personalMessage || null, token_hash: tokenHash, status: "pending", send_email: true, invited_by: context.user.id, invited_user_id: existingUser?.id, expires_at: expiresAt }).select("id").single(); if (error || !invitation) return NextResponse.json({ error: /role|constraint/i.test(error?.message ?? "") ? "Member migration 0030 is required." : "Unable to create the member invitation." }, { status: 500 });
    await audit(context.tenant.id, context.user.id, "tenant.member.invitation_attempted", invitation.id, { role: input.role }); const origin = (process.env.NEXT_PUBLIC_APP_URL || new URL(request.url).origin).replace(/\/+$/, ""); const delivery = await deliverTeamInvitation({ tenantId: context.tenant.id, tenantName: context.tenant.name, email, firstName: input.firstName, personalMessage: input.personalMessage, acceptUrl: `${origin}/invite/accept?token=${encodeURIComponent(token)}`, invitationId: invitation.id });
    await admin.from("tenant_invitations").update({ status: delivery.accepted ? "sent" : "failed", sent_at: delivery.accepted ? now : null, failed_at: delivery.accepted ? null : now, delivery_error: delivery.accepted ? null : delivery.error, invited_user_id: ("invitedUserId" in delivery ? delivery.invitedUserId : undefined) ?? existingUser?.id ?? null, updated_at: now }).eq("id", invitation.id).eq("tenant_id", context.tenant.id); if (!delivery.accepted) return NextResponse.json({ error: delivery.error ?? "The invitation was not delivered." }, { status: 424 }); return NextResponse.json({ invited: true });
  }
  if (input.action === "tag") { const { error } = await admin.from("member_tags").insert({ tenant_id: context.tenant.id, name: input.name, color: input.color, description: input.description, created_by: context.user.id }); if (error) return NextResponse.json({ error: /duplicate/i.test(error.message) ? "That tag already exists." : "Unable to create the tag." }, { status: 500 }); return NextResponse.json({ saved: true }); }
  const membership = await memberRecord(admin, context.tenant.id, input.membershipId); if (!membership) return NextResponse.json({ error: "Audience member not found." }, { status: 404 }); let error: { message: string } | null = null;
  if (input.action === "profile") {
    ({ error } = await admin.from("tenant_memberships").update({ lifecycle_stage: input.lifecycleStage, audience_source: input.audienceSource, updated_at: now }).eq("id", membership.id).eq("tenant_id", context.tenant.id).in("role", ["member","guest"])); if (!error) ({ error } = await admin.from("tenant_member_profiles").upsert({ tenant_id: context.tenant.id, membership_id: membership.id, user_id: membership.user_id, preferred_name: input.preferredName, job_title: input.jobTitle, organization: input.organization, phone: input.phone, location: input.location, timezone: input.timezone, bio: input.bio, updated_at: now }, { onConflict: "membership_id" }));
  } else if (input.action === "status") ({ error } = await admin.from("tenant_memberships").update({ status: input.status, deactivated_at: input.status === "active" ? null : now, updated_at: now }).eq("id", membership.id).eq("tenant_id", context.tenant.id).in("role", ["member","guest"]));
  else if (input.action === "plan") { const permissions = await getTenantPermissionSet(context.role); if (!permissions.has("tenant.memberships.manage")) return NextResponse.json({ error: "Membership plan permission is required." }, { status: 403 }); const { data: current } = await admin.from("member_subscriptions").select("id").eq("tenant_id", context.tenant.id).eq("user_id", membership.user_id).order("updated_at", { ascending: false }).limit(1).maybeSingle(); if (input.planId) { const { data: plan } = await admin.from("tenant_membership_plans").select("id").eq("tenant_id", context.tenant.id).eq("id", input.planId).maybeSingle(); if (!plan) return NextResponse.json({ error: "Membership plan not found." }, { status: 404 }); ({ error } = current ? await admin.from("member_subscriptions").update({ plan_id: input.planId, status: input.status, assignment_type: input.assignmentType, updated_at: now }).eq("id", current.id).eq("tenant_id", context.tenant.id) : await admin.from("member_subscriptions").insert({ tenant_id: context.tenant.id, user_id: membership.user_id, plan_id: input.planId, status: input.status, assignment_type: input.assignmentType, updated_at: now })); } else if (current) ({ error } = await admin.from("member_subscriptions").update({ status: "cancelled", updated_at: now }).eq("id", current.id).eq("tenant_id", context.tenant.id)); }
  else if (input.action === "segments") { const result = await context.supabase.rpc("replace_member_segments", { target_membership: membership.id, target_tags: input.tagIds, target_groups: input.groupIds }); error = result.error; }
  else ({ error } = await admin.from("member_notes").insert({ tenant_id: context.tenant.id, membership_id: membership.id, body: input.body, created_by: context.user.id }));
  if (error) return NextResponse.json({ error: /tenant_member_profiles|member_tags|member_notes|audience_source|schema cache/i.test(error.message) ? "Member migration 0030 is required." : "Unable to update the member." }, { status: 500 }); await audit(context.tenant.id, context.user.id, `tenant.member.${input.action}_saved`, membership.id); return NextResponse.json({ saved: true });
}

export async function DELETE(request: NextRequest) {
  const context = await getActiveTenantWithPermission("tenant.members.manage"); if (!context) return NextResponse.json({ error: "Member management permission is required." }, { status: 403 }); const kind = request.nextUrl.searchParams.get("kind"); const id = request.nextUrl.searchParams.get("id"); if (!id || !z.string().uuid().safeParse(id).success || !["note","tag"].includes(kind ?? "")) return NextResponse.json({ error: "A valid member record is required." }, { status: 400 });
  const table = kind === "note" ? "member_notes" : "member_tags"; const { error } = await createAdminClient().from(table).delete().eq("id", id).eq("tenant_id", context.tenant.id); if (error) return NextResponse.json({ error: "Unable to remove the member record." }, { status: 500 }); return NextResponse.json({ deleted: true });
}
