"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, RefreshCw, RotateCcw, Sparkles, X } from "lucide-react";
import { Button, Card } from "@/components/ui";

type Insight = { id: string; insight_type: string; title: string; qualified_summary: string; supporting_metrics: Record<string, number>; severity: string; recommended_action: string; status: string; updated_at: string };
export function AdminInsightsManager() {
  const [items, setItems] = useState<Insight[]>([]); const [canManage, setCanManage] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/insights", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result.insights ?? []); setCanManage(Boolean(result.canManage)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Insights are unavailable."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function act(id: string, action: "review" | "dismiss" | "reopen") { const response = await fetch("/api/insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action }) }); if (!response.ok) { const result = await response.json(); setError(result.error ?? "Unable to update the insight."); return; } await load(); }
  return <section aria-labelledby="administrator-insights"><div><h2 id="administrator-insights" className="flex items-center gap-2 font-display text-2xl font-bold"><Sparkles className="h-5 w-5 text-accent-700" /> Administrator insights</h2><p className="mt-2 text-sm text-brand-600">Qualified, rules-based operational signals. A person must review the underlying records before acting.</p></div>{error && <p role="alert" className="mt-4 text-sm font-semibold text-red-700">{error}</p>}{loading ? <Card className="mt-4"><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Calculating insights…</p></Card> : <div className="mt-4 grid gap-4 lg:grid-cols-2">{items.map((item) => <Card key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-bold uppercase text-accent-700">{item.insight_type} · {item.severity}</span><span className="rounded-full bg-brand-100 px-2 py-1 text-xs font-bold capitalize">{item.status}</span></div><h3 className="mt-3 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-brand-600">{item.qualified_summary}</p><dl className="mt-3 grid grid-cols-2 gap-2">{Object.entries(item.supporting_metrics ?? {}).map(([label, value]) => <div key={label} className="rounded-lg bg-brand-50 p-2"><dt className="text-xs text-brand-500">{label.replace(/([A-Z])/g, " $1")}</dt><dd className="font-bold">{value}</dd></div>)}</dl><p className="mt-3 text-sm"><strong>Suggested review:</strong> {item.recommended_action}</p>{canManage && <div className="mt-4 flex flex-wrap gap-2">{item.status === "active" ? <><Button size="sm" onClick={() => void act(item.id, "review")}><Check className="h-4 w-4" /> Mark reviewed</Button><Button size="sm" variant="secondary" onClick={() => void act(item.id, "dismiss")}><X className="h-4 w-4" /> Dismiss</Button></> : <Button size="sm" variant="secondary" onClick={() => void act(item.id, "reopen")}><RotateCcw className="h-4 w-4" /> Reopen</Button>}</div>}</Card>)}</div>}</section>;
}
