"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Bot, CheckCircle2, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card, Field, Input, Textarea } from "@/components/ui";

type Source = { sourceType: string; sourceId: string; title: string; url: string; approved: boolean };
type Settings = { enabled?: boolean; coach_name?: string; welcome_message?: string; disclaimer_text?: string; crisis_message?: string; tone?: string; system_instructions?: string; citations_required?: boolean; retain_message_content?: boolean; max_requests_per_hour?: number };

export function AiCoachSettingsManager() {
  const [settings, setSettings] = useState<Settings>({}); const [sources, setSources] = useState<Source[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/ai/coach/settings", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load AI Coach settings."); setSettings(result.settings ?? {}); setSources(result.sources ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load AI Coach settings."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function request(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); const response = await fetch("/api/ai/coach/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to save AI Coach settings."); else { setMessage(success); await load(); } setSaving(false); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void request({ action: "settings", enabled: data.get("enabled") === "on", coachName: data.get("coachName"), welcomeMessage: data.get("welcomeMessage"), disclaimerText: data.get("disclaimerText"), crisisMessage: data.get("crisisMessage"), tone: data.get("tone"), systemInstructions: data.get("systemInstructions"), citationsRequired: data.get("citationsRequired") === "on", retainMessageContent: data.get("retainMessageContent") === "on", maxRequestsPerHour: Number(data.get("maxRequestsPerHour")) }, "AI Coach settings saved."); }
  if (loading) return <Card><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Loading AI Coach settings…</p></Card>;
  return <div className="space-y-6"><div><h1 className="font-display text-3xl font-extrabold text-brand-900">Member AI Coach</h1><p className="mt-2 text-sm text-brand-600">Control the member experience, safety notice, approved knowledge, citations, and limits.</p></div>{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <Card><div className="flex gap-3"><Bot className="h-6 w-6 text-accent-700" /><div><h2 className="font-display text-xl font-bold">Coach behavior</h2><p className="text-sm text-brand-500">A verified default provider must also be enabled.</p></div></div><form onSubmit={save} className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Coach name" htmlFor="coach-name"><Input id="coach-name" name="coachName" defaultValue={settings.coach_name ?? "AI Coach"} required /></Field><Field label="Hourly requests per member" htmlFor="coach-limit"><Input id="coach-limit" name="maxRequestsPerHour" type="number" min="1" max="200" defaultValue={settings.max_requests_per_hour ?? 20} required /></Field><Field label="Welcome message" htmlFor="coach-welcome" className="md:col-span-2"><Textarea id="coach-welcome" name="welcomeMessage" defaultValue={settings.welcome_message ?? "How can I support your learning today?"} required /></Field><Field label="Tone and persona" htmlFor="coach-tone"><Textarea id="coach-tone" name="tone" defaultValue={settings.tone ?? "warm, practical, and respectful"} required /></Field><Field label="Additional system instructions" htmlFor="coach-system"><Textarea id="coach-system" name="systemInstructions" defaultValue={settings.system_instructions ?? ""} /></Field><Field label="Member disclaimer" htmlFor="coach-disclaimer" className="md:col-span-2"><Textarea id="coach-disclaimer" name="disclaimerText" className="min-h-24" defaultValue={settings.disclaimer_text ?? "This AI provides educational guidance based on this organization’s content. It is not medical, legal, mental-health, pastoral, or emergency advice."} required /></Field><Field label="Crisis escalation message" htmlFor="coach-crisis" className="md:col-span-2"><Textarea id="coach-crisis" name="crisisMessage" className="min-h-24" defaultValue={settings.crisis_message ?? "If you or someone else may be in immediate danger, contact local emergency services or a qualified crisis service now."} required /></Field><div className="space-y-3 text-sm"><label className="flex gap-2"><input type="checkbox" name="enabled" defaultChecked={settings.enabled ?? false} /> Enable member AI Coach</label><label className="flex gap-2"><input type="checkbox" name="citationsRequired" defaultChecked={settings.citations_required ?? true} /> Require source citations</label><label className="flex gap-2"><input type="checkbox" name="retainMessageContent" defaultChecked={settings.retain_message_content ?? false} /> Retain message content</label></div><div className="self-end"><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save Coach settings"}</Button></div></form></Card>
    <Card><div className="flex gap-3"><ShieldCheck className="h-6 w-6 text-accent-700" /><div><h2 className="font-display text-xl font-bold">Approved knowledge sources</h2><p className="text-sm text-brand-500">Only selected published content can be retrieved. Source text is treated as untrusted reference material.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{sources.map((source) => <label key={`${source.sourceType}:${source.sourceId}`} className="flex cursor-pointer items-start gap-3 rounded-xl border border-brand-200 p-4"><input type="checkbox" className="mt-1" checked={source.approved} disabled={saving} onChange={(event) => void request({ action: "source", sourceType: source.sourceType, sourceId: source.sourceId, approved: event.target.checked }, event.target.checked ? "Knowledge source approved." : "Knowledge source excluded.")} /><div><p className="font-bold text-brand-900">{source.title}</p><p className="mt-1 text-xs font-semibold uppercase text-brand-500">{source.sourceType}</p></div>{source.approved && <CheckCircle2 className="ml-auto h-5 w-5 text-green-600" />}</label>)}{!sources.length && <p className="text-sm text-brand-500">Publish content with a meaningful description or transcript to make it available here.</p>}</div></Card>
  </div>;
}
