"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Copy, ExternalLink, Save } from "lucide-react";
import { BrandingManager } from "@/components/dashboard/BrandingManager";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type FormValue = string | boolean | Record<string, string>;
type Form = Record<string, FormValue> & { socialLinks: Record<string, string> };
const defaults: Form = {
  legalName: "", communityName: "", podcastName: "", displayName: "", tagline: "", description: "", tenantType: "", primaryCategory: "", secondaryCategories: "",
  supportEmail: "", contactEmail: "", slug: "", visibility: "private_link", welcomeHeading: "", welcomeMessage: "", memberHomeCta: "",
  communityTerminology: "Community", memberSupportUrl: "", defaultMemberLandingPage: "welcome", allowMemberDirectory: false,
  allowMemberMessaging: true, allowMemberDiscussions: true, allowMemberContentSearch: true, primaryCtaLabel: "Join the Community", primaryCtaUrl: "",
  secondaryCtaLabel: "Sign In", secondaryCtaUrl: "", aboutPurpose: "", founderName: "", intendedAudience: "", memberExpectations: "", communityValues: "",
  websiteUrl: "", seoTitle: "", seoDescription: "", seoImageUrl: "", socialLinks: {}
};
const tabs = ["Identity", "Branding", "Public Page", "Links & Social", "Member Experience", "Sharing", "SEO", "Advanced"];
const social = ["Facebook", "Instagram", "LinkedIn", "YouTube", "TikTok", "X", "Podcast Website", "Podcast Feed", "Booking", "Donation", "Shop"];

export function CommunitySettingsManager() {
  const [tab, setTab] = useState("Identity"); const [form, setForm] = useState<Form>(defaults); const [publicUrl, setPublicUrl] = useState("");
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(true);
  const load = useCallback(async () => { setBusy(true); const response = await fetch("/api/community-settings", { cache: "no-store" }); const result = await response.json();
    if (!response.ok) setMessage(result.error || "Unable to load Community Settings."); else { const b=result.branding||{}, s=result.settings||{}; setPublicUrl(result.publicUrl); setForm({ ...defaults,
      legalName:b.legal_name||"", communityName:b.community_name||result.tenant.name, podcastName:b.podcast_name||"", displayName:b.display_name||result.tenant.name,
      tagline:b.tagline||"", description:b.full_description||"", tenantType:b.tenant_type||"", primaryCategory:b.primary_category||"", secondaryCategories:(b.secondary_categories||[]).join(", "),
      supportEmail:b.support_email||"", contactEmail:b.public_contact_email||"", slug:result.tenant.slug, visibility:s.visibility||"private_link", welcomeHeading:s.welcome_heading||"",
      welcomeMessage:s.welcome_message||"", memberHomeCta:s.member_home_cta||"", communityTerminology:s.community_terminology||"Community", memberSupportUrl:s.member_support_url||"",
      defaultMemberLandingPage:s.default_member_landing_page||"welcome", allowMemberDirectory:Boolean(s.allow_member_directory), allowMemberMessaging:s.allow_member_messaging!==false,
      allowMemberDiscussions:s.allow_member_discussions!==false, allowMemberContentSearch:s.allow_member_content_search!==false, primaryCtaLabel:s.primary_cta_label||"Join the Community",
      primaryCtaUrl:s.primary_cta_url||"", secondaryCtaLabel:s.secondary_cta_label||"Sign In", secondaryCtaUrl:s.secondary_cta_url||"", aboutPurpose:s.about_purpose||"",
      founderName:s.founder_name||"", intendedAudience:s.intended_audience||"", memberExpectations:s.member_expectations||"", communityValues:s.community_values||"", websiteUrl:s.website_url||"",
      seoTitle:s.seo_title||"", seoDescription:s.seo_description||"", seoImageUrl:s.seo_image_url||"", socialLinks:s.social_links||{}
    }); } setBusy(false); }, []);
  useEffect(()=>{void load();},[load]);
  const update=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  const identityFields = useMemo(()=>[["legalName","Legal or organization name"],["communityName","Community name"],["podcastName","Podcast name (optional)"],["displayName","Display name"],["tagline","Short tagline"],["tenantType","Tenant type"],["primaryCategory","Primary category"],["secondaryCategories","Secondary categories (comma separated)"],["supportEmail","Public support email"],["contactEmail","Public contact email"]],[]);
  async function save(action:"draft"|"publish") { setBusy(true); const response=await fetch("/api/community-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,secondaryCategories:String(form.secondaryCategories).split(",").map(v=>v.trim()).filter(Boolean),action})}); const result=await response.json(); setMessage(response.ok?`${action==="publish"?"Published":"Draft saved"}. Community identity is now consistent across approved views.`:result.error||"Unable to save."); if(response.ok)setPublicUrl(result.publicUrl); setBusy(false); }
  function submit(event:FormEvent){event.preventDefault();void save("draft");}
  if (busy && !form.communityName) return <Card><p>Loading Community Settings…</p></Card>;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">My Brand</p><h1 className="mt-2 font-display text-3xl font-extrabold text-brand-900">Community Settings</h1><p className="mt-2 text-sm text-brand-600">Control how your community appears to administrators, members, visitors, and email recipients.</p></div>
    {message&&<p role="status" className="rounded-xl border border-brand-200 bg-white px-4 py-3 text-sm font-semibold text-brand-700">{message}</p>}
    <div className="flex gap-2 overflow-x-auto" role="tablist">{tabs.map(item=><button key={item} type="button" role="tab" aria-selected={tab===item} onClick={()=>setTab(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab===item?"bg-brand-900 text-white":"bg-white text-brand-700"}`}>{item}</button>)}</div>
    {tab==="Branding"?<BrandingManager/>:<form onSubmit={submit}><Card className="grid gap-5 md:grid-cols-2">
      {tab==="Identity"&&<>{identityFields.map(([key,label])=><Field key={key} label={label} htmlFor={`community-${key}`} className={key==="description"?"md:col-span-2":""}><Input id={`community-${key}`} type={key.toLowerCase().includes("email")?"email":"text"} value={String(form[key])} required={["communityName","displayName"].includes(key)} onChange={e=>update(key,e.target.value)}/></Field>)}<Field label="Full description" htmlFor="community-description" className="md:col-span-2"><Textarea id="community-description" value={String(form.description)} onChange={e=>update("description",e.target.value)}/></Field></>}
      {tab==="Public Page"&&<><Field label="Public visibility" htmlFor="community-visibility"><Select id="community-visibility" value={String(form.visibility)} onChange={e=>update("visibility",e.target.value)}><option value="public">Publicly discoverable</option><option value="private_link">Private but link-accessible</option><option value="invite_only">Invite only</option><option value="coming_soon">Opening soon</option><option value="waitlist">Waitlist</option><option value="paused">Temporarily paused</option></Select></Field><Field label="Founder or host" htmlFor="founder"><Input id="founder" value={String(form.founderName)} onChange={e=>update("founderName",e.target.value)}/></Field>{[["aboutPurpose","Community purpose"],["intendedAudience","Intended audience"],["memberExpectations","What members can expect"],["communityValues","Community values"]].map(([key,label])=><Field key={key} label={label} htmlFor={key}><Textarea id={key} value={String(form[key])} onChange={e=>update(key,e.target.value)}/></Field>)}{[["primaryCtaLabel","Primary call to action"],["primaryCtaUrl","Primary action URL"],["secondaryCtaLabel","Secondary call to action"],["secondaryCtaUrl","Secondary action URL"]].map(([key,label])=><Field key={key} label={label} htmlFor={key}><Input id={key} type={key.endsWith("Url")?"url":"text"} value={String(form[key])} onChange={e=>update(key,e.target.value)}/></Field>)}</>}
      {tab==="Links & Social"&&<><Field label="Primary website" htmlFor="websiteUrl"><Input id="websiteUrl" type="url" value={String(form.websiteUrl)} onChange={e=>update("websiteUrl",e.target.value)}/></Field>{social.map(label=>{const key=label.toLowerCase().replaceAll(" ","_");return <Field key={key} label={label} htmlFor={`social-${key}`}><Input id={`social-${key}`} type="url" value={form.socialLinks[key]||""} onChange={e=>setForm(current=>({...current,socialLinks:{...current.socialLinks,[key]:e.target.value}}))}/></Field>})}</>}
      {tab==="Member Experience"&&<><Field label="Welcome-page heading" htmlFor="welcomeHeading"><Input id="welcomeHeading" value={String(form.welcomeHeading)} onChange={e=>update("welcomeHeading",e.target.value)}/></Field><Field label="Member-home call to action" htmlFor="memberHomeCta"><Input id="memberHomeCta" value={String(form.memberHomeCta)} onChange={e=>update("memberHomeCta",e.target.value)}/></Field><Field label="Welcome message" htmlFor="welcomeMessage" className="md:col-span-2"><Textarea id="welcomeMessage" value={String(form.welcomeMessage)} onChange={e=>update("welcomeMessage",e.target.value)}/></Field><Field label="Community terminology" htmlFor="communityTerminology"><Input id="communityTerminology" value={String(form.communityTerminology)} onChange={e=>update("communityTerminology",e.target.value)}/></Field><Field label="Member support link" htmlFor="memberSupportUrl"><Input id="memberSupportUrl" type="url" value={String(form.memberSupportUrl)} onChange={e=>update("memberSupportUrl",e.target.value)}/></Field><Field label="Default member landing page" htmlFor="defaultLanding"><Select id="defaultLanding" value={String(form.defaultMemberLandingPage)} onChange={e=>update("defaultMemberLandingPage",e.target.value)}><option value="welcome">Welcome</option><option value="library">Content Library</option><option value="community">Community</option></Select></Field><div className="space-y-2">{[["allowMemberDirectory","Member directory"],["allowMemberMessaging","Member messaging"],["allowMemberDiscussions","Member discussions"],["allowMemberContentSearch","Content search"]].map(([key,label])=><label key={key} className="flex gap-3 text-sm font-semibold"><input type="checkbox" checked={Boolean(form[key])} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div></>}
      {tab==="Sharing"&&<><Field label="Tenant slug" htmlFor="community-slug"><Input id="community-slug" value={String(form.slug)} onChange={e=>update("slug",e.target.value.toLowerCase())}/></Field><Field label="Current public URL" htmlFor="public-url"><Input id="public-url" readOnly value={publicUrl}/></Field><div className="flex gap-2 md:col-span-2"><Button type="button" variant="secondary" onClick={()=>void navigator.clipboard.writeText(publicUrl)}><Copy className="h-4 w-4"/>Copy Community Link</Button><Button href={publicUrl} target="_blank" variant="secondary"><ExternalLink className="h-4 w-4"/>Preview Public Page</Button><Button href="/dashboard/community/share">Open Share Community</Button></div></>}
      {tab==="SEO"&&<>{[["seoTitle","SEO title"],["seoDescription","SEO description"],["seoImageUrl","Social sharing image URL"]].map(([key,label])=><Field key={key} label={label} htmlFor={key} className={key==="seoDescription"?"md:col-span-2":""}>{key==="seoDescription"?<Textarea id={key} value={String(form[key])} onChange={e=>update(key,e.target.value)}/>:<Input id={key} type={key.endsWith("Url")?"url":"text"} value={String(form[key])} onChange={e=>update(key,e.target.value)}/>}</Field>)}</>}
      {tab==="Advanced"&&<><div className="md:col-span-2 rounded-xl bg-brand-50 p-4 text-sm text-brand-700"><strong>Managed URL:</strong> {publicUrl}<br/>Custom-domain automation remains deferred. Configure verified custom domains from the existing domain workflow.</div></>}
      <div className="flex flex-wrap gap-3 md:col-span-2"><Button type="submit" disabled={busy}><Save className="h-4 w-4"/>Save Draft</Button><Button type="button" disabled={busy} onClick={()=>void save("publish")}>Publish Changes</Button><Button href={`/demo/${String(form.slug)}/welcome`} variant="secondary">Preview Member View</Button><Button href={publicUrl} target="_blank" variant="secondary">Preview Public Page</Button></div>
    </Card></form>}
  </div>;
}
