"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Eye, EyeOff, Flag, Lock, Pin, RefreshCw, ShieldCheck, Unlock } from "lucide-react";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type Space = { id: string; name: string; guidelines: string; posting_policy: string; featured: boolean; sort_order: number; status: string };
type Post = { id: string; space_id: string; title: string; body: string; status: string; is_pinned: boolean; is_locked: boolean; moderation_reason: string | null; created_at: string };
type Comment = { id: string; post_id: string; body: string; status: string; moderation_reason: string | null; created_at: string };
type Report = { id: string; post_id: string | null; comment_id: string | null; reason: string; details: string; status: string; created_at: string };

export function CommunityModerationManager() {
  const [spaces, setSpaces] = useState<Space[]>([]); const [posts, setPosts] = useState<Post[]>([]); const [comments, setComments] = useState<Comment[]>([]); const [reports, setReports] = useState<Report[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/community/moderation", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load moderation."); setSpaces(result.spaces ?? []); setPosts(result.posts ?? []); setComments(result.comments ?? []); setReports(result.reports ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load moderation."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); const response = await fetch("/api/community/moderation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to apply moderation."); else { setMessage(success); await load(); } setSaving(false); }
  function reason(operation: string) { if (operation !== "hide") return ""; return window.prompt("Reason for hiding this contribution:", "Community guideline violation") ?? ""; }
  if (loading) return <Card><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Loading moderation queue…</p></Card>;
  return <div className="space-y-6"><div className="border-t border-brand-200 pt-6"><div className="flex items-center gap-2"><ShieldCheck className="h-6 w-6 text-accent-700" /><h2 className="font-display text-2xl font-bold">Community governance</h2></div><p className="mt-2 text-sm text-brand-600">Configure spaces, review reports, and moderate contributions.</p></div>{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <Card><h3 className="font-display text-xl font-bold">Space settings</h3><div className="mt-4 space-y-4">{spaces.map((space) => <form key={space.id} className="grid gap-3 rounded-xl border border-brand-200 p-4 md:grid-cols-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act({ action: "space", id: space.id, guidelines: data.get("guidelines"), postingPolicy: data.get("postingPolicy"), featured: data.get("featured") === "on", sortOrder: Number(data.get("sortOrder")) }, `${space.name} settings saved.`); }}><div className="md:col-span-3"><p className="font-bold">{space.name}</p><p className="text-xs capitalize text-brand-500">{space.status}</p></div><Field label="Posting" htmlFor={`posting-${space.id}`}><Select id={`posting-${space.id}`} name="postingPolicy" defaultValue={space.posting_policy}><option value="members">Members can post</option><option value="managers">Managers post only</option></Select></Field><Field label="Order" htmlFor={`order-${space.id}`}><Input id={`order-${space.id}`} name="sortOrder" type="number" min="0" defaultValue={space.sort_order} /></Field><label className="flex items-center gap-2 pt-7"><input type="checkbox" name="featured" defaultChecked={space.featured} /> Featured</label><Field label="Guidelines" htmlFor={`guidelines-${space.id}`} className="md:col-span-3"><Textarea id={`guidelines-${space.id}`} name="guidelines" defaultValue={space.guidelines} /></Field><div className="md:col-span-3"><Button type="submit" size="sm" disabled={saving}>Save space settings</Button></div></form>)}</div></Card>
    <Card><h3 className="flex items-center gap-2 font-display text-xl font-bold"><Flag className="h-5 w-5 text-red-600" /> Reports</h3><div className="mt-4 space-y-3">{reports.filter((report) => report.status === "open").map((report) => <div key={report.id} className="rounded-xl border border-red-100 bg-red-50 p-4"><p className="font-bold capitalize">{report.reason}</p><p className="mt-1 text-sm">{report.details || "No additional details."}</p><p className="mt-1 text-xs text-brand-500">{report.post_id ? "Discussion" : "Reply"} · {new Date(report.created_at).toLocaleString()}</p><div className="mt-3 flex gap-2"><Button type="button" size="sm" onClick={() => void act({ action: "report", id: report.id, status: "reviewed" }, "Report marked reviewed.")}>Reviewed</Button><Button type="button" size="sm" variant="secondary" onClick={() => void act({ action: "report", id: report.id, status: "dismissed" }, "Report dismissed.")}>Dismiss</Button></div></div>)}{!reports.some((report) => report.status === "open") && <p className="text-sm text-brand-500">No open reports.</p>}</div></Card>
    <Card><h3 className="font-display text-xl font-bold">Recent discussions</h3><div className="mt-4 divide-y">{posts.map((post) => <div key={post.id} className="py-4"><div className="flex flex-wrap items-start gap-2"><div className="min-w-48 flex-1"><p className="font-bold">{post.title}</p><p className="line-clamp-2 text-sm text-brand-600">{post.body}</p><p className="mt-1 text-xs capitalize text-brand-500">{post.status}{post.moderation_reason ? ` · ${post.moderation_reason}` : ""}</p></div><Button type="button" size="sm" variant="secondary" onClick={() => void act({ action: "post", id: post.id, operation: post.is_pinned ? "unpin" : "pin", reason: "" }, post.is_pinned ? "Discussion unpinned." : "Discussion pinned.")}><Pin className="h-4 w-4" />{post.is_pinned ? "Unpin" : "Pin"}</Button><Button type="button" size="sm" variant="secondary" onClick={() => void act({ action: "post", id: post.id, operation: post.is_locked ? "unlock" : "lock", reason: "" }, post.is_locked ? "Discussion unlocked." : "Discussion locked.")}>{post.is_locked ? <Unlock className="h-4 w-4" /> : <Lock className="h-4 w-4" />}{post.is_locked ? "Unlock" : "Lock"}</Button><Button type="button" size="sm" variant="secondary" onClick={() => { const operation = post.status === "hidden" ? "restore" : "hide"; void act({ action: "post", id: post.id, operation, reason: reason(operation) }, operation === "hide" ? "Discussion hidden." : "Discussion restored."); }}>{post.status === "hidden" ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}{post.status === "hidden" ? "Restore" : "Hide"}</Button></div></div>)}</div></Card>
    <Card><h3 className="font-display text-xl font-bold">Recent replies</h3><div className="mt-4 divide-y">{comments.map((comment) => <div key={comment.id} className="flex gap-3 py-3"><div className="flex-1"><p className="line-clamp-2 text-sm">{comment.body}</p><p className="text-xs capitalize text-brand-500">{comment.status}</p></div><Button type="button" size="sm" variant="secondary" onClick={() => { const operation = comment.status === "hidden" ? "restore" : "hide"; void act({ action: "comment", id: comment.id, operation, reason: reason(operation) }, operation === "hide" ? "Reply hidden." : "Reply restored."); }}>{comment.status === "hidden" ? "Restore" : "Hide"}</Button></div>)}</div></Card>
  </div>;
}
