"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Download, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card, Select, Textarea } from "@/components/ui";

type Request = { id: string; subject_user_id: string; request_type: string; status: string; request_details: string; resolution_notes: string; resolved_at?: string; created_at: string };
type Data = { tenant: { name: string }; requests: Request[]; users: Record<string, { email?: string; name?: string }> };
export function DataGovernanceManager() {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/data-governance", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load data governance."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function resolve(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); const values = new FormData(event.currentTarget); try { const response = await fetch("/api/data-governance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: values.get("status"), resolutionNotes: values.get("resolutionNotes") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage("Data-rights request updated and audited."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update the request."); } finally { setSaving(false); } }
  if (loading) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading governance queue…</p></Card>; if (!data) return <Card><p className="text-red-700">{error || "Data governance is unavailable."}</p></Card>;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Governance</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><ShieldCheck className="h-7 w-7" /> Data governance</h1><p className="mt-2 text-sm text-brand-600">Review member data-rights requests and export a tenant-scoped operational audit history for {data.tenant.name}.</p></div>{message && <p role="status" className="rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-800">{message}</p>}{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>}<Card><h2 className="font-display text-xl font-bold">Audit export</h2><p className="mt-2 text-sm text-brand-600">Downloads up to the latest 5,000 tenant audit events as CSV. Every export is itself recorded in the audit history.</p><a href="/api/data-governance?export=audit" className="mt-4 inline-flex items-center gap-2 rounded-lg bg-accent-600 px-4 py-2 text-sm font-bold text-white"><Download className="h-4 w-4" /> Export audit CSV</a></Card><div className="space-y-4">{data.requests.length ? data.requests.map((item) => { const user = data.users[item.subject_user_id]; return <Card key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="font-display text-lg font-bold capitalize">{item.request_type} request</p><p className="text-sm text-brand-500">{user?.name || user?.email || item.subject_user_id}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold capitalize">{item.status.replace("_", " ")}</span></div><p className="mt-4 rounded-lg bg-brand-50 p-3 text-sm text-brand-700">{item.request_details}</p><p className="mt-2 text-xs text-brand-400">Submitted {new Date(item.created_at).toLocaleString()}</p><form className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto]" onSubmit={(event) => void resolve(event, item.id)}><Select name="status" aria-label="Resolution status" defaultValue={item.status === "submitted" ? "in_review" : item.status}><option value="in_review">In review</option><option value="completed">Completed</option><option value="denied">Denied</option></Select><Textarea name="resolutionNotes" aria-label="Resolution notes" defaultValue={item.resolution_notes} placeholder="Record the review outcome. Do not include unnecessary sensitive data." /><Button type="submit" disabled={saving}>Save resolution</Button></form></Card>; }) : <Card><p className="text-sm text-brand-500">No data-rights requests are waiting.</p></Card>}</div></div>;
}
