"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FileText, Plus, RefreshCw, Tags, Trash2 } from "lucide-react";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type Episode = { show_notes?: string; key_takeaways?: string[]; reflection_questions?: string[]; duration_seconds?: number | null; season_number?: number | null; episode_number?: number | null; featured?: boolean };
type Transcript = { content: string; language: string; status: string; allow_download: boolean };
type Resource = { id: string; title: string; description: string; url: string; resource_type: string; allow_download: boolean; sort_order: number };

export function EpisodeContentManager({ episodeId }: { episodeId: string }) {
  const endpoint = `/api/podcast/${episodeId}/details`; const [episode, setEpisode] = useState<Episode>({}); const [transcript, setTranscript] = useState<Transcript | null>(null); const [resources, setResources] = useState<Resource[]>([]); const [tags, setTags] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(endpoint, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load episode details."); setEpisode(result.episode ?? {}); setTranscript(result.transcript); setResources(result.resources ?? []); setTags(result.tags ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load episode details."); } finally { setLoading(false); } }, [endpoint]); useEffect(() => { void load(); }, [load]);
  async function save(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to save episode details."); else { setMessage(success); await load(); } setSaving(false); }
  function metadata(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void save({ kind: "metadata", showNotes: data.get("showNotes"), keyTakeaways: lines(data.get("takeaways")), reflectionQuestions: lines(data.get("questions")), durationSeconds: numberOrNull(data.get("duration")), seasonNumber: numberOrNull(data.get("season")), episodeNumber: numberOrNull(data.get("episodeNumber")), featured: data.get("featured") === "on" }, "Episode learning details saved."); }
  function transcriptSave(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void save({ kind: "transcript", content: data.get("content"), language: data.get("language"), status: data.get("status"), allowDownload: data.get("allowDownload") === "on" }, "Transcript saved."); }
  function resource(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void save({ kind: "resource", title: data.get("title"), description: data.get("description"), url: data.get("url"), resourceType: data.get("resourceType"), allowDownload: data.get("allowDownload") === "on", sortOrder: resources.length }, "Episode resource added.").then(() => form.reset()); }
  async function remove(id: string) { if (!window.confirm("Remove this episode resource?")) return; setSaving(true); const response = await fetch(`${endpoint}?resourceId=${id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to remove resource."); else { setMessage("Episode resource removed."); await load(); } setSaving(false); }
  if (loading) return <Card><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Loading episode content…</p></Card>;
  return <div className="space-y-5">{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <Card><h2 className="font-display text-xl font-bold">Episode learning experience</h2><form onSubmit={metadata} className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Season" htmlFor="episode-season"><Input id="episode-season" name="season" type="number" min="1" defaultValue={episode.season_number ?? ""} /></Field><Field label="Episode number" htmlFor="episode-number"><Input id="episode-number" name="episodeNumber" type="number" min="1" defaultValue={episode.episode_number ?? ""} /></Field><Field label="Duration (seconds)" htmlFor="episode-duration"><Input id="episode-duration" name="duration" type="number" min="1" defaultValue={episode.duration_seconds ?? ""} /></Field><Field label="Show notes" htmlFor="episode-notes" className="md:col-span-3"><Textarea id="episode-notes" name="showNotes" className="min-h-32" defaultValue={episode.show_notes ?? ""} /></Field><Field label="Key takeaways (one per line)" htmlFor="episode-takeaways"><Textarea id="episode-takeaways" name="takeaways" defaultValue={(episode.key_takeaways ?? []).join("\n")} /></Field><Field label="Reflection questions (one per line)" htmlFor="episode-questions" className="md:col-span-2"><Textarea id="episode-questions" name="questions" defaultValue={(episode.reflection_questions ?? []).join("\n")} /></Field><label className="flex items-center gap-2"><input type="checkbox" name="featured" defaultChecked={episode.featured ?? false} /> Feature this episode</label><div className="md:col-span-2"><Button type="submit" disabled={saving}>Save learning details</Button></div></form></Card>
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><FileText className="h-5 w-5 text-accent-700" /> Transcript</h2><form onSubmit={transcriptSave} className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Language" htmlFor="transcript-language"><Input id="transcript-language" name="language" defaultValue={transcript?.language ?? "en"} required /></Field><Field label="Status" htmlFor="transcript-status"><Select id="transcript-status" name="status" defaultValue={transcript?.status ?? "draft"}><option value="draft">Draft</option><option value="published">Published</option></Select></Field><label className="flex items-center gap-2 pt-7"><input type="checkbox" name="allowDownload" defaultChecked={transcript?.allow_download ?? false} /> Allow transcript download</label><Field label="Transcript text" htmlFor="transcript-content" className="md:col-span-3"><Textarea id="transcript-content" name="content" className="min-h-64" defaultValue={transcript?.content ?? ""} /></Field><div className="md:col-span-3"><Button type="submit" disabled={saving}>Save transcript</Button></div></form></Card>
    <Card><h2 className="font-display text-xl font-bold">Episode resources</h2><form onSubmit={resource} className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Title" htmlFor="resource-title"><Input id="resource-title" name="title" required /></Field><Field label="Type" htmlFor="resource-type"><Select id="resource-type" name="resourceType"><option value="link">Link</option><option value="download">Download</option><option value="worksheet">Worksheet</option><option value="transcript">Transcript</option><option value="book">Book</option><option value="article">Article</option><option value="video">Video</option><option value="audio">Audio</option></Select></Field><Field label="URL" htmlFor="resource-url"><Input id="resource-url" name="url" type="url" required /></Field><Field label="Description" htmlFor="resource-description" className="md:col-span-2"><Input id="resource-description" name="description" /></Field><label className="flex items-center gap-2"><input type="checkbox" name="allowDownload" defaultChecked /> Allow download</label><div className="md:col-span-3"><Button type="submit" size="sm" disabled={saving}><Plus className="h-4 w-4" /> Add resource</Button></div></form><div className="mt-5 divide-y">{resources.map((item) => <div key={item.id} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="font-bold">{item.title}</p><p className="text-xs capitalize text-brand-500">{item.resource_type} · {item.allow_download ? "Downloadable" : "View only"}</p></div><a href={item.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-accent-700">Open</a><button type="button" aria-label={`Remove ${item.title}`} onClick={() => void remove(item.id)} className="p-2 text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div></Card>
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><Tags className="h-5 w-5 text-accent-700" /> Topics</h2><form className="mt-4 flex gap-3" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void save({ kind: "tags", tags: String(data.get("tags") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean) }, "Episode topics saved."); }}><Input name="tags" aria-label="Episode topics" defaultValue={tags.join(", ")} placeholder="healing, leadership, wellness" /><Button type="submit" disabled={saving}>Save topics</Button></form></Card>
  </div>;
}

function lines(value: FormDataEntryValue | null) { return String(value ?? "").split("\n").map((item) => item.trim()).filter(Boolean); }
function numberOrNull(value: FormDataEntryValue | null) { return value ? Number(value) : null; }
