"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, PlayCircle, RefreshCw, Trash2, Users } from "lucide-react";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type EventDetails = { starts_at: string; ends_at?: string | null; timezone?: string; event_format?: string; venue_name?: string; venue_address?: string; capacity?: number | null; registration_required?: boolean; registration_deadline?: string | null; waitlist_enabled?: boolean; member_instructions?: string; featured?: boolean };
type Registration = { id: string; user_id: string; status: string; registered_at: string };
type Replay = { id: string; title: string; description: string; url: string; access_level: string; status: string; allow_download: boolean };
type Profile = { id: string; full_name: string | null };

export function EventExperienceManager({ eventId }: { eventId: string }) {
  const endpoint = `/api/events/${eventId}/details`; const [event, setEvent] = useState<EventDetails | null>(null); const [registrations, setRegistrations] = useState<Registration[]>([]); const [replays, setReplays] = useState<Replay[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(endpoint, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load event details."); setEvent(result.event); setRegistrations(result.registrations ?? []); setReplays(result.replays ?? []); setProfiles(result.profiles ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load event details."); } finally { setLoading(false); } }, [endpoint]); useEffect(() => { void load(); }, [load]);
  async function save(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); setMessage(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to save event details."); setMessage(success); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save event details."); } finally { setSaving(false); } }
  const profileNames = useMemo(() => new Map(profiles.map((profile) => [profile.id, profile.full_name || "Member"])), [profiles]);
  if (loading) return <Card><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Loading event experience…</p></Card>;
  if (!event) return <Card><p className="text-sm text-red-700">{error || "Event details are unavailable."}</p></Card>;
  return <div className="space-y-5">{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><CalendarClock className="h-5 w-5 text-accent-700" /> Event experience</h2><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={(formEvent: FormEvent<HTMLFormElement>) => { formEvent.preventDefault(); const data = new FormData(formEvent.currentTarget); void save({ kind: "metadata", endsAt: isoOrNull(data.get("endsAt")), timezone: data.get("timezone"), eventFormat: data.get("eventFormat"), venueName: data.get("venueName"), venueAddress: data.get("venueAddress"), capacity: numberOrNull(data.get("capacity")), registrationRequired: data.get("registrationRequired") === "on", registrationDeadline: isoOrNull(data.get("registrationDeadline")), waitlistEnabled: data.get("waitlistEnabled") === "on", memberInstructions: data.get("memberInstructions"), featured: data.get("featured") === "on" }, "Event experience saved."); }}>
      <Field label="Ends at" htmlFor="event-ends"><Input id="event-ends" name="endsAt" type="datetime-local" defaultValue={localDateTime(event.ends_at)} /></Field><Field label="Time zone" htmlFor="event-timezone"><Input id="event-timezone" name="timezone" defaultValue={event.timezone ?? "UTC"} placeholder="America/New_York" required /></Field><Field label="Format" htmlFor="event-format"><Select id="event-format" name="eventFormat" defaultValue={event.event_format ?? "online"}><option value="online">Online</option><option value="in_person">In person</option><option value="hybrid">Hybrid</option></Select></Field>
      <Field label="Venue name" htmlFor="event-venue"><Input id="event-venue" name="venueName" defaultValue={event.venue_name ?? ""} /></Field><Field label="Venue address" htmlFor="event-address" className="md:col-span-2"><Input id="event-address" name="venueAddress" defaultValue={event.venue_address ?? ""} /></Field><Field label="Capacity" htmlFor="event-capacity" hint="Leave blank for unlimited."><Input id="event-capacity" name="capacity" type="number" min="1" defaultValue={event.capacity ?? ""} /></Field><Field label="Registration closes" htmlFor="event-deadline"><Input id="event-deadline" name="registrationDeadline" type="datetime-local" defaultValue={localDateTime(event.registration_deadline)} /></Field><div className="space-y-2 pt-7"><label className="flex items-center gap-2"><input type="checkbox" name="registrationRequired" defaultChecked={event.registration_required ?? true} /> Registration required</label><label className="flex items-center gap-2"><input type="checkbox" name="waitlistEnabled" defaultChecked={event.waitlist_enabled ?? true} /> Enable waitlist</label><label className="flex items-center gap-2"><input type="checkbox" name="featured" defaultChecked={event.featured ?? false} /> Featured event</label></div>
      <Field label="Member instructions" htmlFor="event-instructions" className="md:col-span-3"><Textarea id="event-instructions" name="memberInstructions" className="min-h-28" defaultValue={event.member_instructions ?? ""} /></Field><div className="md:col-span-3"><Button type="submit" disabled={saving}>Save event experience</Button></div>
    </form></Card>
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><Users className="h-5 w-5 text-accent-700" /> Attendees</h2><p className="mt-1 text-sm text-brand-500">{registrations.filter((item) => item.status === "registered" || item.status === "attended").length} confirmed · {registrations.filter((item) => item.status === "waitlisted").length} waitlisted</p><div className="mt-4 divide-y">{registrations.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-48 flex-1"><p className="font-bold">{profileNames.get(item.user_id) ?? "Member"}</p><p className="text-xs text-brand-500">Registered {new Date(item.registered_at).toLocaleString()}</p></div><Select aria-label={`Status for ${profileNames.get(item.user_id) ?? "member"}`} value={item.status} onChange={(change) => void save({ kind: "attendee", registrationId: item.id, status: change.target.value }, "Attendance updated.")} disabled={saving} className="max-w-44"><option value="registered">Registered</option><option value="waitlisted">Waitlisted</option><option value="attended">Attended</option><option value="no_show">No show</option><option value="cancelled">Cancelled</option></Select></div>)}{!registrations.length && <p className="py-5 text-sm text-brand-500">No registrations yet.</p>}</div></Card>
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><PlayCircle className="h-5 w-5 text-accent-700" /> Replays</h2><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={(formEvent: FormEvent<HTMLFormElement>) => { formEvent.preventDefault(); const form = formEvent.currentTarget; const data = new FormData(form); void save({ kind: "replay", title: data.get("title"), description: data.get("description"), url: data.get("url"), accessLevel: data.get("accessLevel"), status: data.get("status"), allowDownload: data.get("allowDownload") === "on" }, "Replay added.").then(() => form.reset()); }}><Field label="Title" htmlFor="replay-title"><Input id="replay-title" name="title" required /></Field><Field label="Replay URL" htmlFor="replay-url"><Input id="replay-url" name="url" type="url" required /></Field><Field label="Access" htmlFor="replay-access"><Select id="replay-access" name="accessLevel"><option value="member">Members</option><option value="paid">Paid members</option><option value="public">Public</option></Select></Field><Field label="Description" htmlFor="replay-description"><Input id="replay-description" name="description" /></Field><Field label="Status" htmlFor="replay-status"><Select id="replay-status" name="status"><option value="draft">Draft</option><option value="published">Published</option></Select></Field><label className="flex items-center gap-2 pt-7"><input type="checkbox" name="allowDownload" /> Allow download</label><div className="md:col-span-3"><Button type="submit" size="sm" disabled={saving}>Add replay</Button></div></form><div className="mt-4 divide-y">{replays.map((replay) => <div key={replay.id} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="font-bold">{replay.title}</p><p className="text-xs capitalize text-brand-500">{replay.status} · {replay.access_level}</p></div><a href={replay.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-accent-700">Open</a><button type="button" aria-label={`Remove ${replay.title}`} onClick={async () => { if (!window.confirm("Remove this replay?")) return; const response = await fetch(`${endpoint}?replayId=${replay.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to remove replay."); else { setMessage("Replay removed."); await load(); } }} className="p-2 text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div></Card>
  </div>;
}

function isoOrNull(value: FormDataEntryValue | null) { return value ? new Date(String(value)).toISOString() : null; }
function numberOrNull(value: FormDataEntryValue | null) { return value ? Number(value) : null; }
function localDateTime(value?: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
