"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { MailPlus, RefreshCw, Search, Tag, Trash2, UserRound, Users } from "lucide-react";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type Membership = { id: string; user_id: string; role: string; status: string; created_at: string; joined_at?: string; last_active_at?: string; audience_source: string; lifecycle_stage: string };
type TenantProfile = { membership_id: string; preferred_name: string; job_title: string; organization: string; phone: string; location: string; timezone: string; bio: string };
type AuthUser = { email?: string; lastSignInAt?: string; metadata?: Record<string, unknown> };
type Plan = { id: string; name: string; status: string; plan_type: string };
type Subscription = { id: string; user_id: string; plan_id: string; status: string; assignment_type: string };
type MemberTag = { id: string; name: string; color: string; description: string };
type Group = { id: string; name: string; status: string };
type Note = { id: string; membership_id: string; body: string; created_at: string };
type Directory = { tenant: { name: string }; canManage: boolean; memberships: Membership[]; profiles: TenantProfile[]; subscriptions: Subscription[]; plans: Plan[]; tags: MemberTag[]; tagAssignments: Array<{ membership_id: string; tag_id: string }>; groups: Group[]; groupMembers: Array<{ group_id: string; user_id: string }>; notes: Note[]; invitations: Array<{ id: string; email: string; first_name: string; last_name: string; role: string; status: string; expires_at: string }>; authUsers: Record<string, AuthUser> };

export function MemberDirectoryManager() {
  const [data, setData] = useState<Directory | null>(null); const [selectedId, setSelectedId] = useState(""); const [query, setQuery] = useState(""); const [stage, setStage] = useState("all"); const [status, setStatus] = useState("all"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/members", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load members."); setData(result); setSelectedId((current) => current && result.memberships.some((item: Membership) => item.id === current) ? current : result.memberships[0]?.id ?? ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load members."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function mutate(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/members", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to update the member."); setMessage(success); await load(); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update the member."); return false; } finally { setSaving(false); } }
  const filtered = useMemo(() => (data?.memberships ?? []).filter((member) => { const auth = data?.authUsers[member.user_id]; const profile = data?.profiles.find((item) => item.membership_id === member.id); const text = `${auth?.email ?? ""} ${displayName(auth, profile)} ${profile?.organization ?? ""}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (stage === "all" || member.lifecycle_stage === stage) && (status === "all" || member.status === status); }), [data, query, stage, status]);
  const selected = data?.memberships.find((member) => member.id === selectedId); const profile = data?.profiles.find((item) => item.membership_id === selectedId); const auth = selected ? data?.authUsers[selected.user_id] : undefined; const subscription = selected ? data?.subscriptions.find((item) => item.user_id === selected.user_id) : undefined; const selectedTags = new Set((data?.tagAssignments ?? []).filter((item) => item.membership_id === selectedId).map((item) => item.tag_id)); const selectedGroups = new Set((data?.groupMembers ?? []).filter((item) => item.user_id === selected?.user_id).map((item) => item.group_id));
  if (loading) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading member directory…</p></Card>; if (!data) return <Card><p className="text-red-700">{error || "Member directory unavailable."}</p></Card>;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Audience</p><h1 className="mt-2 font-display text-3xl font-extrabold text-brand-900">Members</h1><p className="mt-2 text-sm text-brand-600">Manage audience profiles, access, plans, segments, groups, and relationship notes for {data.tenant.name}.</p></div>{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-3"><Card><Users className="h-5 w-5 text-accent-700" /><p className="mt-3 text-2xl font-extrabold">{data.memberships.filter((item) => item.status === "active").length}</p><p className="text-sm text-brand-600">Active audience members</p></Card><Card><UserRound className="h-5 w-5 text-accent-700" /><p className="mt-3 text-2xl font-extrabold">{data.memberships.filter((item) => item.lifecycle_stage === "onboarding").length}</p><p className="text-sm text-brand-600">Onboarding</p></Card><Card><MailPlus className="h-5 w-5 text-accent-700" /><p className="mt-3 text-2xl font-extrabold">{data.invitations.filter((item) => ["pending","sent"].includes(item.status)).length}</p><p className="text-sm text-brand-600">Open invitations</p></Card></div>
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Invite audience member</h2><form className="mt-4 grid gap-4 md:grid-cols-4" onSubmit={async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); if (await mutate({ action: "invite", firstName: values.get("firstName"), lastName: values.get("lastName"), email: values.get("email"), role: values.get("role"), personalMessage: values.get("personalMessage") }, "Member invitation sent.")) form.reset(); }}><Field label="First name" htmlFor="member-first"><Input id="member-first" name="firstName" required /></Field><Field label="Last name" htmlFor="member-last"><Input id="member-last" name="lastName" /></Field><Field label="Email" htmlFor="member-email"><Input id="member-email" name="email" type="email" required /></Field><Field label="Access" htmlFor="member-role"><Select id="member-role" name="role"><option value="member">Member</option><option value="guest">Guest</option></Select></Field><Field label="Personal message" htmlFor="member-message" className="md:col-span-3"><Input id="member-message" name="personalMessage" /></Field><div className="pt-7"><Button type="submit" disabled={saving}><MailPlus className="h-4 w-4" /> Send invitation</Button></div></form>{data.invitations.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{data.invitations.map((invite) => <span key={invite.id} className="rounded-full bg-brand-100 px-3 py-1 text-xs font-semibold">{invite.email} · {invite.status}</span>)}</div>}</Card>}
    <div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><Card><div className="grid gap-3"><label className="relative"><span className="sr-only">Search members</span><Search className="absolute left-3 top-3 h-4 w-4 text-brand-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search members" className="pl-9" /></label><div className="grid grid-cols-2 gap-2"><Select aria-label="Filter lifecycle" value={stage} onChange={(event) => setStage(event.target.value)}><option value="all">All stages</option>{["lead","onboarding","active","at_risk","inactive","alumni"].map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</Select><Select aria-label="Filter status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select></div></div><div className="mt-4 divide-y">{filtered.map((member) => { const memberProfile = data.profiles.find((item) => item.membership_id === member.id); const memberAuth = data.authUsers[member.user_id]; return <button key={member.id} type="button" onClick={() => setSelectedId(member.id)} className={`w-full px-2 py-4 text-left ${selectedId === member.id ? "bg-accent-50" : ""}`}><p className="font-bold text-brand-900">{displayName(memberAuth, memberProfile)}</p><p className="text-xs text-brand-500">{memberAuth?.email || "Email unavailable"}</p><div className="mt-2 flex gap-2"><span className="rounded-full bg-brand-100 px-2 py-0.5 text-[10px] font-bold capitalize">{member.status}</span><span className="rounded-full bg-accent-100 px-2 py-0.5 text-[10px] font-bold capitalize text-accent-800">{member.lifecycle_stage.replace("_", " ")}</span></div></button>; })}{!filtered.length && <p className="py-6 text-center text-sm text-brand-500">No members match these filters.</p>}</div></Card>
      {selected ? <div className="space-y-5"><Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-bold">{displayName(auth, profile)}</h2><p className="text-sm text-brand-500">{auth?.email || "Email unavailable"} · Joined {new Date(selected.joined_at || selected.created_at).toLocaleDateString()}</p>{auth?.lastSignInAt && <p className="mt-1 text-xs text-brand-400">Last sign-in {new Date(auth.lastSignInAt).toLocaleString()}</p>}</div>{data.canManage && <Select aria-label="Member status" value={selected.status} onChange={(event) => void mutate({ action: "status", membershipId: selected.id, status: event.target.value }, "Member status updated.")} disabled={saving} className="max-w-40"><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select>}</div></Card>
        <Card><h3 className="font-display text-xl font-bold">Profile and lifecycle</h3><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); void mutate({ action: "profile", membershipId: selected.id, lifecycleStage: values.get("lifecycleStage"), audienceSource: values.get("audienceSource"), preferredName: values.get("preferredName"), jobTitle: values.get("jobTitle"), organization: values.get("organization"), phone: values.get("phone"), location: values.get("location"), timezone: values.get("timezone"), bio: values.get("bio") }, "Member profile saved."); }}><Field label="Preferred name" htmlFor="profile-name"><Input id="profile-name" name="preferredName" defaultValue={profile?.preferred_name ?? ""} /></Field><Field label="Lifecycle" htmlFor="profile-stage"><Select id="profile-stage" name="lifecycleStage" defaultValue={selected.lifecycle_stage}>{["lead","onboarding","active","at_risk","inactive","alumni"].map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</Select></Field><Field label="Source" htmlFor="profile-source"><Select id="profile-source" name="audienceSource" defaultValue={selected.audience_source}>{["direct","invitation","signup","checkout","import","admin"].map((item) => <option key={item} value={item}>{item}</option>)}</Select></Field><Field label="Job title" htmlFor="profile-job"><Input id="profile-job" name="jobTitle" defaultValue={profile?.job_title ?? ""} /></Field><Field label="Organization" htmlFor="profile-org"><Input id="profile-org" name="organization" defaultValue={profile?.organization ?? ""} /></Field><Field label="Phone" htmlFor="profile-phone"><Input id="profile-phone" name="phone" defaultValue={profile?.phone ?? ""} /></Field><Field label="Location" htmlFor="profile-location"><Input id="profile-location" name="location" defaultValue={profile?.location ?? ""} /></Field><Field label="Time zone" htmlFor="profile-timezone"><Input id="profile-timezone" name="timezone" defaultValue={profile?.timezone ?? "UTC"} /></Field><Field label="Bio" htmlFor="profile-bio" className="md:col-span-3"><Textarea id="profile-bio" name="bio" defaultValue={profile?.bio ?? ""} /></Field>{data.canManage && <div className="md:col-span-3"><Button type="submit" disabled={saving}>Save profile</Button></div>}</form></Card>
        {data.canManage && <Card><h3 className="font-display text-xl font-bold">Membership plan</h3><form className="mt-4 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); void mutate({ action: "plan", membershipId: selected.id, planId: values.get("planId") || null, status: values.get("planStatus"), assignmentType: values.get("assignmentType") }, "Membership plan updated."); }}><Select name="planId" aria-label="Membership plan" defaultValue={subscription?.plan_id ?? ""} className="max-w-64"><option value="">No plan</option>{data.plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</Select><Select name="planStatus" aria-label="Plan status" defaultValue={subscription?.status ?? "active"} className="max-w-44"><option value="active">Active</option><option value="trialing">Trialing</option><option value="cancelled">Cancelled</option></Select><Select name="assignmentType" aria-label="Assignment type" defaultValue={subscription?.assignment_type === "complimentary" ? "complimentary" : "manual"} className="max-w-48"><option value="manual">Manual</option><option value="complimentary">Complimentary</option></Select><Button type="submit" disabled={saving}>Save plan</Button></form></Card>}
        <Card><h3 className="flex items-center gap-2 font-display text-xl font-bold"><Tag className="h-5 w-5 text-accent-700" /> Tags and groups</h3>{data.canManage && <form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); if (await mutate({ action: "tag", name: values.get("name"), color: values.get("color"), description: values.get("description") }, "Member tag created.")) form.reset(); }}><Input name="name" placeholder="New tag" required /><Input name="color" type="color" defaultValue="#5b46d8" /><Input name="description" placeholder="Description" /><div className="md:col-span-3"><Button type="submit" size="sm">Create tag</Button></div></form>}<form className="mt-5 grid gap-5 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); void mutate({ action: "segments", membershipId: selected.id, tagIds: values.getAll("tagIds"), groupIds: values.getAll("groupIds") }, "Member segments updated."); }}><div><p className="text-sm font-bold">Tags</p><div className="mt-2 space-y-2">{data.tags.map((tag) => <label key={tag.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="tagIds" value={tag.id} defaultChecked={selectedTags.has(tag.id)} /><span className="h-3 w-3 rounded-full" style={{ backgroundColor: tag.color }} />{tag.name}</label>)}</div></div><div><p className="text-sm font-bold">Communication groups</p><div className="mt-2 space-y-2">{data.groups.map((group) => <label key={group.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="groupIds" value={group.id} defaultChecked={selectedGroups.has(group.id)} />{group.name}</label>)}</div></div>{data.canManage && <div className="md:col-span-2"><Button type="submit" disabled={saving}>Save segments</Button></div>}</form></Card>
        {data.canManage && <Card><h3 className="font-display text-xl font-bold">Private member notes</h3><form className="mt-4 flex gap-3" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); if (await mutate({ action: "note", membershipId: selected.id, body: values.get("body") }, "Member note added.")) form.reset(); }}><Textarea name="body" aria-label="New member note" required /><Button type="submit" disabled={saving}>Add note</Button></form><div className="mt-4 divide-y">{data.notes.filter((note) => note.membership_id === selected.id).map((note) => <div key={note.id} className="flex gap-3 py-3"><div className="flex-1"><p className="text-sm text-brand-700">{note.body}</p><p className="mt-1 text-xs text-brand-400">{new Date(note.created_at).toLocaleString()}</p></div><button type="button" aria-label="Delete member note" onClick={async () => { if (!window.confirm("Delete this note?")) return; const response = await fetch(`/api/members?kind=note&id=${note.id}`, { method: "DELETE" }); if (response.ok) await load(); else setError("Unable to remove the note."); }} className="p-2 text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div></Card>}
      </div> : <Card><p className="py-10 text-center text-brand-500">Select a member to view their profile.</p></Card>}</div>
  </div>;
}

function displayName(auth?: AuthUser, profile?: TenantProfile) { const metadataName = auth?.metadata?.full_name ?? auth?.metadata?.name; return profile?.preferred_name || (typeof metadataName === "string" ? metadataName : "") || auth?.email?.split("@")[0] || "Member"; }
