"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FileClock, RefreshCw, Trash2 } from "lucide-react";
import { Button, Card, Field, Input, Select, Textarea } from "@/components/ui";

type Resource = { full_description?: string; author?: string; file_format?: string; file_size_bytes?: number | null; version_label?: string; allow_download?: boolean; featured?: boolean; publish_date?: string | null };
type Version = { id: string; version_label: string; notes: string; url: string; file_format: string; file_size_bytes: number | null; allow_download: boolean; status: string; created_at: string };

export function ResourceExperienceManager({ resourceId }: { resourceId: string }) {
  const endpoint = `/api/resources/${resourceId}/details`; const [resource, setResource] = useState<Resource | null>(null); const [versions, setVersions] = useState<Version[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(endpoint, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load resource details."); setResource(result.resource); setVersions(result.versions ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load resource details."); } finally { setLoading(false); } }, [endpoint]); useEffect(() => { void load(); }, [load]);
  async function save(body: Record<string, unknown>, success: string) { setSaving(true); setError(""); setMessage(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to save resource details."); setMessage(success); await load(); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save resource details."); return false; } finally { setSaving(false); } }
  if (loading) return <Card><p className="flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4 animate-spin" /> Loading resource experience…</p></Card>; if (!resource) return <Card><p className="text-red-700">{error || "Resource details are unavailable."}</p></Card>;
  return <div className="space-y-5">{message && <div role="status" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
    <Card><h2 className="font-display text-xl font-bold">Resource experience</h2><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void save({ kind: "metadata", fullDescription: data.get("fullDescription"), author: data.get("author"), fileFormat: data.get("fileFormat"), fileSizeBytes: numberOrNull(data.get("fileSizeBytes")), versionLabel: data.get("versionLabel"), allowDownload: data.get("allowDownload") === "on", featured: data.get("featured") === "on", publishDate: isoOrNull(data.get("publishDate")) }, "Resource details saved."); }}><Field label="Author or source" htmlFor="resource-author"><Input id="resource-author" name="author" defaultValue={resource.author ?? ""} /></Field><Field label="File format" htmlFor="resource-format"><Input id="resource-format" name="fileFormat" defaultValue={resource.file_format ?? ""} placeholder="PDF" /></Field><Field label="File size (bytes)" htmlFor="resource-size"><Input id="resource-size" name="fileSizeBytes" type="number" min="0" defaultValue={resource.file_size_bytes ?? ""} /></Field><Field label="Current version" htmlFor="resource-version"><Input id="resource-version" name="versionLabel" defaultValue={resource.version_label ?? "1.0"} required /></Field><Field label="Publish date" htmlFor="resource-publish"><Input id="resource-publish" name="publishDate" type="datetime-local" defaultValue={localDateTime(resource.publish_date)} /></Field><div className="space-y-2 pt-7"><label className="flex items-center gap-2"><input type="checkbox" name="allowDownload" defaultChecked={resource.allow_download ?? true} /> Allow download</label><label className="flex items-center gap-2"><input type="checkbox" name="featured" defaultChecked={resource.featured ?? false} /> Featured resource</label></div><Field label="Full description" htmlFor="resource-full-description" className="md:col-span-3"><Textarea id="resource-full-description" name="fullDescription" className="min-h-36" defaultValue={resource.full_description ?? ""} /></Field><div className="md:col-span-3"><Button type="submit" disabled={saving}>Save resource details</Button></div></form></Card>
    <Card><h2 className="flex items-center gap-2 font-display text-xl font-bold"><FileClock className="h-5 w-5 text-accent-700" /> Version history</h2><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if (await save({ kind: "version", versionLabel: data.get("versionLabel"), notes: data.get("notes"), url: data.get("url"), fileFormat: data.get("fileFormat"), fileSizeBytes: numberOrNull(data.get("fileSizeBytes")), allowDownload: data.get("allowDownload") === "on", status: data.get("status") }, "Resource version added.")) form.reset(); }}><Field label="Version" htmlFor="version-label"><Input id="version-label" name="versionLabel" required /></Field><Field label="URL" htmlFor="version-url"><Input id="version-url" name="url" type="url" required /></Field><Field label="Status" htmlFor="version-status"><Select id="version-status" name="status"><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></Select></Field><Field label="Format" htmlFor="version-format"><Input id="version-format" name="fileFormat" /></Field><Field label="File size (bytes)" htmlFor="version-size"><Input id="version-size" name="fileSizeBytes" type="number" min="0" /></Field><label className="flex items-center gap-2 pt-7"><input type="checkbox" name="allowDownload" defaultChecked /> Allow download</label><Field label="Release notes" htmlFor="version-notes" className="md:col-span-3"><Textarea id="version-notes" name="notes" /></Field><div className="md:col-span-3"><Button type="submit" size="sm" disabled={saving}>Add version</Button></div></form><div className="mt-5 divide-y">{versions.map((version) => <div key={version.id} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="font-bold">Version {version.version_label}</p><p className="text-xs capitalize text-brand-500">{version.status}{version.file_format ? ` · ${version.file_format}` : ""}{version.file_size_bytes ? ` · ${formatBytes(version.file_size_bytes)}` : ""}</p>{version.notes && <p className="mt-1 text-sm text-brand-600">{version.notes}</p>}</div><a href={version.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-accent-700">Open</a><button type="button" aria-label={`Remove version ${version.version_label}`} onClick={async () => { if (!window.confirm("Remove this resource version?")) return; const response = await fetch(`${endpoint}?versionId=${version.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to remove version."); else { setMessage("Resource version removed."); await load(); } }} className="p-2 text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div></Card>
  </div>;
}

function numberOrNull(value: FormDataEntryValue | null) { return value ? Number(value) : null; }
function isoOrNull(value: FormDataEntryValue | null) { return value ? new Date(String(value)).toISOString() : null; }
function localDateTime(value?: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / 1024 ** 2).toFixed(1)} MB`; }
