"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, Download, ExternalLink, Share2 } from "lucide-react";
import { Button, Card, Field, Input } from "@/components/ui";

export function ShareCommunityManager(){const [base,setBase]=useState("");const [source,setSource]=useState("");const [medium,setMedium]=useState("");const [campaign,setCampaign]=useState("");const [label,setLabel]=useState("Join My Community");const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/community-sharing",{cache:"no-store"});const result=await response.json();if(response.ok)setBase(result.publicUrl);else setMessage(result.error||"Unable to load sharing tools.");},[]);useEffect(()=>{void load();},[load]);
 const url=useMemo(()=>{if(!base)return "";const value=new URL(base);if(source)value.searchParams.set("utm_source",source);if(medium)value.searchParams.set("utm_medium",medium);if(campaign)value.searchParams.set("utm_campaign",campaign);return value.toString();},[base,source,medium,campaign]);
 const markup=`<a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="${label}">${label}</a>`;
 const caption=`Join me inside our community: ${url}`;const copy=async(value:string,success:string)=>{await navigator.clipboard.writeText(value);setMessage(success);};
 return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">My Link</p><h1 className="mt-2 font-display text-3xl font-extrabold text-brand-900">Share Community</h1><p className="mt-2 text-sm text-brand-600">Give people one clear place to discover and join your community.</p></div>{message&&<p role="status" className="rounded-xl border border-brand-200 bg-white px-4 py-3 text-sm font-semibold text-brand-700">{message}</p>}
 <Card><h2 className="font-display text-xl font-bold text-brand-900">Primary Community Link</h2><p className="mt-3 break-all rounded-lg bg-brand-50 p-3 font-mono text-sm">{url||"Loading…"}</p><div className="mt-4 flex flex-wrap gap-2"><Button type="button" onClick={()=>void copy(url,"Community link copied.")}><Copy className="h-4 w-4"/>Copy Link</Button><Button href={url} target="_blank" variant="secondary"><ExternalLink className="h-4 w-4"/>Open Public Page</Button><Button href={`/api/community-sharing/qr?format=png&target=${encodeURIComponent(url)}`} download variant="secondary"><Download className="h-4 w-4"/>Download QR PNG</Button><Button href={`/api/community-sharing/qr?format=svg&target=${encodeURIComponent(url)}`} download variant="secondary"><Download className="h-4 w-4"/>Download QR SVG</Button></div></Card>
 <Card><h2 className="font-display text-xl font-bold text-brand-900">Campaign Tracking</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Source" htmlFor="share-source"><Input id="share-source" value={source} onChange={e=>setSource(e.target.value)} placeholder="newsletter"/></Field><Field label="Medium" htmlFor="share-medium"><Input id="share-medium" value={medium} onChange={e=>setMedium(e.target.value)} placeholder="email"/></Field><Field label="Campaign" htmlFor="share-campaign"><Input id="share-campaign" value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="community-launch"/></Field></div></Card>
 <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="font-display text-xl font-bold text-brand-900">Social Sharing</h2><p className="mt-2 text-sm text-brand-600">Copy a truthful caption for email, Facebook, LinkedIn, X, Instagram, or TikTok. No automatic posting is implied.</p><div className="mt-4 flex flex-wrap gap-2"><Button type="button" onClick={()=>void copy(caption,"Social caption copied.")}><Share2 className="h-4 w-4"/>Copy Caption</Button><Button href={`mailto:?subject=${encodeURIComponent(label)}&body=${encodeURIComponent(caption)}`} variant="secondary">Share by Email</Button></div></Card>
 <Card><h2 className="font-display text-xl font-bold text-brand-900">Website Button</h2><Field label="Button label" htmlFor="button-label" className="mt-4"><Input id="button-label" value={label} onChange={e=>setLabel(e.target.value)}/></Field><pre className="mt-3 overflow-x-auto rounded-lg bg-brand-900 p-3 text-xs text-white"><code>{markup}</code></pre><Button type="button" className="mt-3" onClick={()=>void copy(markup,"Accessible website link copied.")}><Copy className="h-4 w-4"/>Copy HTML</Button></Card></div>
 </div>}
