import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getActiveTenantWithPermission } from "@/lib/tenant-context";
import { publicCommunityUrl } from "@/lib/community-settings";

const schema=z.object({label:z.string().trim().min(2).max(100),targetType:z.enum(["community","signup","resource","membership","event","course","episode"]),targetId:z.string().uuid().optional().or(z.literal("")),source:z.string().trim().max(80).default(""),medium:z.string().trim().max(80).default(""),campaign:z.string().trim().max(120).default(""),content:z.string().trim().max(120).default(""),referrerCode:z.string().trim().max(80).default(""),expiresAt:z.string().datetime().optional().or(z.literal("")),maxUses:z.number().int().positive().max(100000).nullable()});

export async function GET(){const context=await getActiveTenantWithPermission("tenant.members.view");if(!context)return NextResponse.json({error:"Member access is required."},{status:403});const {data,error}=await context.supabase.from("community_share_links").select("*").eq("tenant_id",context.tenant.id).order("created_at",{ascending:false});if(error)return NextResponse.json({error:"Community sharing migration 0044 is required."},{status:503});return NextResponse.json({links:data??[],publicUrl:publicCommunityUrl(context.tenant.slug),tenant:context.tenant});}

export async function POST(request:NextRequest){const context=await getActiveTenantWithPermission("tenant.members.manage");if(!context)return NextResponse.json({error:"Member management permission is required."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Check the share-link settings."},{status:400});const value=parsed.data;const {data,error}=await context.supabase.from("community_share_links").insert({tenant_id:context.tenant.id,label:value.label,target_type:value.targetType,target_id:value.targetId||null,source:value.source||null,medium:value.medium||null,campaign:value.campaign||null,content:value.content||null,referrer_code:value.referrerCode||null,expires_at:value.expiresAt||null,max_uses:value.maxUses,created_by:context.user.id}).select("*").single();if(error)return NextResponse.json({error:"Unable to create the share link."},{status:500});await context.supabase.from("audit_logs").insert({tenant_id:context.tenant.id,user_id:context.user.id,action:"tenant.community_link.created",entity_type:"community_share_link",entity_id:data.id,metadata:{target_type:value.targetType,campaign:value.campaign}});return NextResponse.json({link:data});}
