import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { communitySettingsSchema, paymentFeatureFlags, publicCommunityUrl } from "@/lib/community-settings";

const root=process.cwd();const read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
afterEach(()=>{for(const key of ["STRIPE_PLATFORM_BILLING_ENABLED","STRIPE_CONNECT_ENABLED","LIVE_CHECKOUT_ENABLED","TENANT_PAID_MEMBERSHIPS_ENABLED","TENANT_PRODUCT_PAYMENTS_ENABLED"])delete process.env[key];});

describe("community launch milestone",()=>{
 it("keeps the community name visible with a logo",()=>{expect(read("components/tenant/MemberHeader.tsx")).toContain("{tenantLogo &&");expect(read("components/tenant/MemberHeader.tsx")).toContain("{tenantName}");expect(read("components/BrandMark.tsx")).not.toContain("{!logoUrl && (");});
 it("rejects reserved and invalid slugs",()=>{const base={legalName:"",communityName:"Community",podcastName:"",displayName:"Community",tagline:"",description:"",tenantType:"",primaryCategory:"",secondaryCategories:[],supportEmail:"",contactEmail:"",visibility:"public",welcomeHeading:"",welcomeMessage:"",memberHomeCta:"",communityTerminology:"Community",memberSupportUrl:"",defaultMemberLandingPage:"welcome",allowMemberDirectory:false,allowMemberMessaging:true,allowMemberDiscussions:true,allowMemberContentSearch:true,primaryCtaLabel:"Join",primaryCtaUrl:"",secondaryCtaLabel:"Sign In",secondaryCtaUrl:"",aboutPurpose:"",founderName:"",intendedAudience:"",memberExpectations:"",communityValues:"",websiteUrl:"",socialLinks:{},seoTitle:"",seoDescription:"",seoImageUrl:"",action:"draft"};expect(communitySettingsSchema.safeParse({...base,slug:"admin"}).success).toBe(false);expect(communitySettingsSchema.safeParse({...base,slug:"my-community"}).success).toBe(true);});
 it("builds the managed public URL",()=>{expect(publicCommunityUrl("my-community")).toBe("https://my-community.upnexx.net");});
 it("keeps every payment integration off unless separately enabled",()=>{expect(paymentFeatureFlags()).toEqual({platformBilling:false,stripeConnect:false,liveCheckout:false,paidMemberships:false,productPayments:false});process.env.STRIPE_CONNECT_ENABLED="true";expect(paymentFeatureFlags().stripeConnect).toBe(true);expect(paymentFeatureFlags().liveCheckout).toBe(false);});
 it("adds tenant-scoped public settings, sharing, consent, products, and RLS",()=>{const sql=read("supabase/migrations/0044_community_launch.sql");for(const value of ["tenant_community_settings","community_share_links","community_leads","community_testimonials","tenant_products","enable row level security","consented_at","external_purchase_url"])expect(sql).toContain(value);});
 it("provides public, sharing, QR, and readable AI workflows",()=>{expect(read("app/demo/[tenant-slug]/page.tsx")).toContain("PublicLeadCapture");expect(read("app/api/community-sharing/qr/route.ts")).toContain("QRCode.toBuffer");expect(read("components/dashboard/ShareCommunityManager.tsx")).toContain("Accessible website link copied");expect(read("components/dashboard/CreatorAiStudio.tsx")).toContain("Create From My Content");expect(read("components/dashboard/CreatorAiStudio.tsx")).not.toContain("Associated Source ID");});
 it("records community administration actions",()=>{expect(read("app/api/community-settings/route.ts")).toContain("tenant.public_page.published");expect(read("app/api/community-sharing/route.ts")).toContain("tenant.community_link.created");expect(read("app/api/community-sharing/qr/route.ts")).toContain("tenant.community_qr.generated");expect(read("app/api/public/community/[slug]/leads/route.ts")).toContain("tenant.public_lead.captured");});
});
