import { resolve4, resolve6, resolveCname, resolveTxt } from "node:dns/promises";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getPlatformAccess, getPlatformAdministrator } from "@/lib/platform-context";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

const schema = z.union([
  z.object({ action: z.literal("verify_dns"), id: z.string().uuid() }),
  z.object({ action: z.literal("ssl"), id: z.string().uuid(), status: z.enum(["passed","failed"]), evidenceReference: z.string().trim().min(1).max(1000), notes: z.string().trim().max(5000) }),
  z.object({ action: z.literal("activate"), id: z.string().uuid(), evidenceReference: z.string().trim().min(1).max(1000) }),
  z.object({ action: z.literal("rollback"), id: z.string().uuid(), evidenceReference: z.string().trim().min(1).max(1000), notes: z.string().trim().max(5000) })
]);
const settled = <T,>(result: PromiseSettledResult<T>) => result.status === "fulfilled" ? result.value : [] as unknown as T;
const normalized = (value: string) => value.toLowerCase().replace(/\.$/, "");

export async function GET() { const access = await getPlatformAccess(); if (!access?.permissions.has("platform.audit.view")) return NextResponse.json({ error: "Platform audit permission is required." }, { status: 403 }); const admin = createAdminClient(); const [{ data: domains, error }, { data: attempts }, { data: tenants }] = await Promise.all([admin.from("tenant_domains").select("id,tenant_id,hostname,domain_type,status,is_primary,ssl_status,verification_record_name,verification_record_value,dns_target,dns_verified_at,ssl_verified_at,last_checked_at,failure_reason,canonical_redirect_enabled,activated_at,deactivated_at,created_at,updated_at").eq("domain_type", "custom").order("created_at", { ascending: false }), admin.from("tenant_domain_verification_attempts").select("id,domain_id,tenant_id,check_type,status,evidence_reference,observed,notes,performed_at").order("performed_at", { ascending: false }).limit(500), admin.from("tenants").select("id,name,slug,status")]); if (error) return NextResponse.json({ error: /schema cache|does not exist/i.test(error.message) ? "Custom-domain migration 0039 is required." : "Unable to load custom domains." }, { status: 500 }); return NextResponse.json({ domains: domains ?? [], attempts: attempts ?? [], tenants: tenants ?? [], canManage: access.permissions.has("platform.operations.manage") }, { headers: { "Cache-Control": "no-store" } }); }

export async function POST(request: NextRequest) { const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Check the domain evidence." }, { status: 400 }); const access = await getPlatformAdministrator("platform.operations.manage"); if (!access) return NextResponse.json({ error: "Platform operations management permission is required." }, { status: 403 }); const admin = createAdminClient(); const userClient = await createClient(); const input = parsed.data; const { data: domain } = await admin.from("tenant_domains").select("id,tenant_id,hostname,status,ssl_status,verification_record_name,verification_record_value,dns_target").eq("id", input.id).eq("domain_type", "custom").maybeSingle(); if (!domain) return NextResponse.json({ error: "Custom domain not found." }, { status: 404 }); const now = new Date().toISOString();
  if (input.action === "verify_dns") { if (domain.status === "active") return NextResponse.json({ error: "Roll back an active domain before running a lifecycle re-verification." }, { status: 409 }); const target = normalized(domain.dns_target || process.env.CUSTOM_DOMAIN_CNAME_TARGET || "app.upnexx.net"); const [txtResult,cnameResult,domain4Result,domain6Result,target4Result,target6Result] = await Promise.allSettled([resolveTxt(domain.verification_record_name),resolveCname(domain.hostname),resolve4(domain.hostname),resolve6(domain.hostname),resolve4(target),resolve6(target)]); const txt = settled(txtResult).flat(); const cnames = settled(cnameResult).map(normalized); const domainAddresses = [...settled(domain4Result),...settled(domain6Result)]; const targetAddresses = new Set([...settled(target4Result),...settled(target6Result)]); const ownershipPassed = txt.includes(domain.verification_record_value); const routePassed = cnames.includes(target) || domainAddresses.some((address) => targetAddresses.has(address)); const evidenceReference = `dns-query:${now}`; const observed = { ownership_record_found: ownershipPassed, route_target_found: routePassed, cname_targets: cnames, address_match_count: domainAddresses.filter((address) => targetAddresses.has(address)).length };
    await admin.from("tenant_domain_verification_attempts").insert([{ domain_id: domain.id, tenant_id: domain.tenant_id, check_type: "ownership_txt", status: ownershipPassed ? "passed" : "failed", evidence_reference: evidenceReference, observed, performed_by: access.user.id },{ domain_id: domain.id, tenant_id: domain.tenant_id, check_type: "dns_route", status: routePassed ? "passed" : "failed", evidence_reference: evidenceReference, observed, performed_by: access.user.id }]); const failure = !ownershipPassed ? "The ownership TXT record was not found." : !routePassed ? "The hostname does not route to the configured UpNexx target." : ""; const { error } = await admin.from("tenant_domains").update({ status: ownershipPassed && routePassed ? "dns_verified" : "failed", verified_at: ownershipPassed ? now : null, dns_verified_at: ownershipPassed && routePassed ? now : null, last_checked_at: now, failure_reason: failure, updated_by: access.user.id, updated_at: now }).eq("id", domain.id); if (error) return NextResponse.json({ error: "Unable to save DNS verification." }, { status: 500 }); await admin.from("audit_logs").insert({ tenant_id: domain.tenant_id, user_id: access.user.id, action: ownershipPassed && routePassed ? "platform.domain.dns_verified" : "platform.domain.dns_failed", entity_type: "tenant_domain", entity_id: domain.id, metadata: observed }); return NextResponse.json({ ownershipPassed, routePassed }); }
  if (input.action === "ssl") { if (!["dns_verified","inactive"].includes(domain.status)) return NextResponse.json({ error: "DNS ownership and routing must pass before SSL evidence is recorded." }, { status: 409 }); const passed = input.status === "passed"; const { error } = await admin.from("tenant_domains").update({ ssl_status: passed ? "active" : "failed", ssl_verified_at: passed ? now : null, failure_reason: passed ? "" : input.notes || "SSL verification failed.", last_checked_at: now, updated_by: access.user.id, updated_at: now }).eq("id", domain.id); if (error) return NextResponse.json({ error: "Unable to save SSL evidence." }, { status: 500 }); await admin.from("tenant_domain_verification_attempts").insert({ domain_id: domain.id, tenant_id: domain.tenant_id, check_type: "ssl_certificate", status: input.status, evidence_reference: input.evidenceReference, notes: input.notes, performed_by: access.user.id }); await admin.from("audit_logs").insert({ tenant_id: domain.tenant_id, user_id: access.user.id, action: `platform.domain.ssl_${input.status}`, entity_type: "tenant_domain", entity_id: domain.id, metadata: {} }); return NextResponse.json({ saved: true }); }
  if (input.action === "activate") { const { error } = await userClient.rpc("activate_tenant_custom_domain", { target_domain: domain.id, target_evidence_reference: input.evidenceReference }); if (error) return NextResponse.json({ error: /verified_domain_and_ssl_required/i.test(error.message) ? "Verified DNS ownership, routing, and SSL evidence are required before activation." : "Unable to activate the custom domain." }, { status: 409 }); await admin.from("audit_logs").insert({ tenant_id: domain.tenant_id, user_id: access.user.id, action: "platform.domain.activated", entity_type: "tenant_domain", entity_id: domain.id, metadata: {} }); return NextResponse.json({ saved: true }); }
  const { error } = await userClient.rpc("rollback_tenant_custom_domain", { target_domain: domain.id, target_evidence_reference: input.evidenceReference, target_notes: input.notes }); if (error) return NextResponse.json({ error: "Unable to roll back the custom domain." }, { status: 409 }); await admin.from("audit_logs").insert({ tenant_id: domain.tenant_id, user_id: access.user.id, action: "platform.domain.rolled_back", entity_type: "tenant_domain", entity_id: domain.id, metadata: {} }); return NextResponse.json({ saved: true });
}
