"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card, Input, Select, Textarea } from "@/components/ui";

type Check = { id: string; check_key: string; label: string; category: string; status: "pending" | "passed" | "failed" | "waived"; evidence_reference: string; notes: string; verified_at?: string };
type Settings = { incident_contact_name: string; incident_contact_email: string; status_page_url: string; uptime_monitor_name: string; backup_owner_name: string; recovery_owner_name: string; approved_rpo_minutes: number | null; approved_rto_minutes: number | null };
type Recovery = { id: string; verification_type: string; status: string; verified_at: string; evidence_reference: string; measured_recovery_minutes: number | null; recovery_point_age_minutes: number | null };
type Diagnostics = { configuration: string; database: string; storage: string; environment: string; missingConfiguration: string[] };
type Notification = { id: string; category: string; recipient_hint: string; status: string; attempts: number; max_attempts: number; next_attempt_at: string; last_error: string; accepted_at?: string; created_at: string };
type Payload = { settings: Settings; checks: Check[]; recoveryVerifications: Recovery[]; notificationDeliveries: Notification[]; diagnostics: Diagnostics; canManage: boolean };
const numberOrNull = (value: FormDataEntryValue | null) => value === null || value === "" ? null : Number(value);

export function PlatformOperationalReadiness() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/platform/operations", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load operational readiness."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(body: Record<string, unknown>) { setError(""); setMessage(""); const response = await fetch("/api/platform/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to save operational evidence."); return; } setMessage("Operational evidence saved."); await load(); }
  if (!data) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading operational readiness…</p>{error && <span className="text-red-700"> {error}</span>}</Card>;
  const passed = data.checks.filter((item) => item.status === "passed").length; const ready = data.checks.length > 0 && passed === data.checks.length;
  return <div className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Production operations</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><ShieldCheck className="h-7 w-7" /> Operational Readiness</h1><p className="mt-2 text-sm text-brand-600">Evidence is not proof until recorded. Pending stays pending; this console never fabricates a passed production check.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}
    <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-display text-xl font-bold">Production release gate</p><p className="mt-1 text-sm text-brand-600">{passed} of {data.checks.length} checks have recorded passed evidence.</p></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${ready ? "bg-green-100 text-green-800" : "bg-amber-100 text-amber-900"}`}>{ready ? "Evidence complete — operator approval still required" : "Not ready for production release"}</span></div></Card>
    <div className="grid gap-4 md:grid-cols-3">{(["configuration", "database", "storage"] as const).map((key) => <Card key={key}><p className="flex items-center gap-2 text-sm font-bold capitalize"><Activity className="h-4 w-4" /> {key}</p><p className={`mt-2 text-lg font-extrabold capitalize ${data.diagnostics[key] === "passed" ? "text-green-700" : "text-red-700"}`}>{data.diagnostics[key]}</p></Card>)}</div>
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Ownership and recovery objectives</h2><p className="mt-1 text-sm text-brand-500">Store contacts and references only—never credentials or backup secrets.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void save({ action: "settings", incidentContactName: form.get("incidentContactName"), incidentContactEmail: form.get("incidentContactEmail"), statusPageUrl: form.get("statusPageUrl"), uptimeMonitorName: form.get("uptimeMonitorName"), backupOwnerName: form.get("backupOwnerName"), recoveryOwnerName: form.get("recoveryOwnerName"), approvedRpoMinutes: numberOrNull(form.get("approvedRpoMinutes")), approvedRtoMinutes: numberOrNull(form.get("approvedRtoMinutes")) }); }}>
      <Input name="incidentContactName" aria-label="Incident contact name" placeholder="Incident contact name" defaultValue={data.settings.incident_contact_name} /><Input name="incidentContactEmail" type="email" aria-label="Incident contact email" placeholder="Incident contact email" defaultValue={data.settings.incident_contact_email} /><Input name="backupOwnerName" aria-label="Backup owner" placeholder="Backup owner" defaultValue={data.settings.backup_owner_name} /><Input name="recoveryOwnerName" aria-label="Recovery owner" placeholder="Recovery owner" defaultValue={data.settings.recovery_owner_name} /><Input name="uptimeMonitorName" aria-label="Uptime monitor name" placeholder="Uptime monitor name" defaultValue={data.settings.uptime_monitor_name} /><Input name="statusPageUrl" type="url" aria-label="Status page URL" placeholder="https://status.example.com" defaultValue={data.settings.status_page_url} /><Input name="approvedRpoMinutes" type="number" min="1" aria-label="Approved RPO minutes" placeholder="RPO in minutes" defaultValue={data.settings.approved_rpo_minutes ?? ""} /><Input name="approvedRtoMinutes" type="number" min="1" aria-label="Approved RTO minutes" placeholder="RTO in minutes" defaultValue={data.settings.approved_rto_minutes ?? ""} /><div className="md:col-span-2"><Button type="submit">Save operational ownership</Button></div>
    </form></Card>}
    <div className="space-y-4"><h2 className="font-display text-2xl font-bold">Release evidence</h2>{data.checks.map((item) => <Card key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="font-bold">{item.label}</p><p className="text-xs uppercase tracking-wide text-brand-500">{item.category}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold capitalize">{item.status}</span></div>{data.canManage && <form className="mt-4 grid gap-3 md:grid-cols-[160px_1fr]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void save({ action: "check", id: item.id, status: form.get("status"), evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Select name="status" defaultValue={item.status} aria-label={`${item.label} status`}><option value="pending">Pending</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="waived">Waived</option></Select><Input name="evidenceReference" aria-label={`${item.label} evidence reference`} placeholder="Ticket, report, or immutable evidence reference" defaultValue={item.evidence_reference} /><Textarea name="notes" className="md:col-span-2" aria-label={`${item.label} notes`} placeholder="Review notes" defaultValue={item.notes} /><div className="md:col-span-2"><Button type="submit">Save check evidence</Button></div></form>}</Card>)}</div>
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Record a recovery verification</h2><p className="mt-1 text-sm text-brand-500">Records are append-only. Passed exercises require an evidence reference.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void save({ action: "recovery", verificationType: form.get("verificationType"), status: form.get("status"), verifiedAt: new Date(String(form.get("verifiedAt"))).toISOString(), evidenceReference: form.get("evidenceReference"), notes: form.get("notes"), measuredRecoveryMinutes: numberOrNull(form.get("measuredRecoveryMinutes")), recoveryPointAgeMinutes: numberOrNull(form.get("recoveryPointAgeMinutes")) }); }}><Select name="verificationType" aria-label="Verification type"><option value="database_backup">Database backup</option><option value="storage_backup">Storage backup</option><option value="database_restore">Database restore</option><option value="storage_restore">Storage restore</option></Select><Select name="status" aria-label="Verification status"><option value="passed">Passed</option><option value="partial">Partial</option><option value="failed">Failed</option></Select><Input required name="verifiedAt" type="datetime-local" aria-label="Verified at" /><Input name="evidenceReference" aria-label="Recovery evidence reference" placeholder="Evidence reference" /><Input name="measuredRecoveryMinutes" type="number" min="0" aria-label="Measured recovery minutes" placeholder="Measured recovery minutes" /><Input name="recoveryPointAgeMinutes" type="number" min="0" aria-label="Recovery point age minutes" placeholder="Recovery point age minutes" /><Textarea name="notes" className="md:col-span-2" aria-label="Recovery verification notes" placeholder="Exercise notes" /><div className="md:col-span-2"><Button type="submit">Record verification</Button></div></form></Card>}
    <Card><h2 className="font-display text-xl font-bold">Recovery history</h2><div className="mt-4 space-y-3">{data.recoveryVerifications.length ? data.recoveryVerifications.map((item) => <div key={item.id} className="rounded-xl border border-brand-100 p-3"><p className="font-bold capitalize">{item.verification_type.replaceAll("_", " ")} · {item.status}</p><p className="mt-1 text-xs text-brand-500">Production · {new Date(item.verified_at).toLocaleString()} · {item.evidence_reference || "No evidence reference recorded"}</p></div>) : <p className="text-sm text-brand-500">No recovery verification has been recorded. This is intentionally not treated as passed.</p>}</div></Card>
    <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold">Transactional notification delivery</h2><p className="mt-1 text-sm text-brand-500">Privacy-minimized delivery evidence; encrypted message payloads are never shown here.</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold">{data.notificationDeliveries.filter((item) => item.status === "failed").length} failed</span></div><div className="mt-4 space-y-3">{data.notificationDeliveries.length ? data.notificationDeliveries.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-brand-100 p-3"><div><p className="font-bold capitalize">{item.category.replaceAll("_", " ")} · {item.status.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-brand-500">{item.recipient_hint} · Attempt {item.attempts} of {item.max_attempts} · {new Date(item.created_at).toLocaleString()}</p>{item.last_error && <p className="mt-1 text-xs text-red-700">{item.last_error}</p>}</div>{data.canManage && item.status === "failed" && <Button type="button" onClick={() => void save({ action: "retry_notification", id: item.id })}>Retry delivery</Button>}</div>) : <p className="text-sm text-brand-500">No transactional notification deliveries are recorded.</p>}</div></Card>
  </div>;
}
