"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { PackageCheck, RefreshCw } from "lucide-react";
import { Button, Card, Input, Textarea } from "@/components/ui";

type Release = { id: string; release_reference: string; application_version: string; commit_sha: string; artifact_sha256: string; migration_from: number; migration_through: number; status: string; created_at: string; approved_at: string | null; released_at: string | null; deployment_evidence_reference: string };
type Event = { id: string; release_id: string; event_type: string; evidence_reference: string; notes: string; performed_at: string };
type Check = { check_key: string; label: string; status: string; evidence_reference: string; updated_at: string };
type Payload = { releases: Release[]; events: Event[]; checks: Check[]; canManage: boolean; canApprove: boolean };

export function PlatformProductionReleases() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/platform/releases", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load release packages."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(body: Record<string, unknown>) { setError(""); setMessage(""); const response = await fetch("/api/platform/releases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to update the release package."); return; } setMessage(body.action === "create" ? "Immutable release candidate created and awaiting Platform Owner approval." : "Release evidence updated."); await load(); }
  if (!data) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading production release packages...</p>{error && <span className="text-red-700"> {error}</span>}</Card>;
  const blockers = data.checks.filter((check) => !["passed","waived"].includes(check.status));
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Combined direct production release</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><PackageCheck className="h-7 w-7" /> Production Releases</h1><p className="mt-2 text-sm text-brand-600">Freeze the exact commit, artifact digest, migrations, isolation run, quality run, and readiness evidence. This console records approval and deployment evidence; it never deploys code.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}
    <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold">Live release gates</h2><p className="mt-1 text-sm text-brand-600">{blockers.length ? `${blockers.length} gate${blockers.length === 1 ? "" : "s"} still block packaging.` : "All gates are passed or explicitly waived; matching RLS and quality runs are still required."}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${blockers.length ? "bg-amber-100 text-amber-900" : "bg-green-100 text-green-800"}`}>{blockers.length ? "BLOCKED" : "GATES CLEAR"}</span></div>{blockers.length > 0 && <div className="mt-4 space-y-2">{blockers.map((check) => <p key={check.check_key} className="text-sm"><strong>{check.label}</strong> · {check.status}</p>)}</div>}</Card>
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Create immutable candidate</h2><p className="mt-1 text-sm text-brand-500">Run <code>npm run release:preflight</code> from the clean release commit and copy its SHA values. Use the same reference/version as the passed production isolation and quality runs.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "create", releaseReference: form.get("releaseReference"), applicationVersion: form.get("applicationVersion"), commitSha: form.get("commitSha"), artifactSha256: form.get("artifactSha256") }); }}><Input required name="releaseReference" aria-label="Release reference" placeholder="release-2026-08-01" /><Input required name="applicationVersion" aria-label="Application version" placeholder="1.0.0" /><Input required name="commitSha" minLength={40} maxLength={40} pattern="[0-9a-f]{40}" aria-label="Git commit SHA" placeholder="40-character commit SHA" /><Input required name="artifactSha256" minLength={64} maxLength={64} pattern="[0-9a-f]{64}" aria-label="Artifact SHA-256" placeholder="64-character artifact digest" /><div className="md:col-span-2"><Button type="submit" disabled={blockers.length > 0}>Freeze release candidate</Button></div></form></Card>}
    <div className="space-y-4">{data.releases.length ? data.releases.map((release) => <Card key={release.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-display text-xl font-bold">{release.release_reference}</h2><p className="mt-1 text-sm text-brand-600">Version {release.application_version} · migrations {String(release.migration_from).padStart(4,"0")}–{String(release.migration_through).padStart(4,"0")} · {new Date(release.created_at).toLocaleString()}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold uppercase">{release.status.replaceAll("_", " ")}</span></div><div className="mt-3 rounded-xl border border-brand-100 p-3 font-mono text-xs"><p className="break-all">commit {release.commit_sha}</p><p className="mt-1 break-all">artifact sha256 {release.artifact_sha256}</p></div>
      {data.canApprove && release.status === "awaiting_approval" && <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "approve", id: release.id, evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Input required name="evidenceReference" aria-label={`Approval evidence for ${release.release_reference}`} placeholder="Approval/ticket reference" /><Textarea name="notes" aria-label={`Approval notes for ${release.release_reference}`} placeholder="Approval scope and conditions" /><div className="md:col-span-2"><Button type="submit">Approve production release</Button></div></form>}
      {data.canApprove && release.status === "approved" && <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "release", id: release.id, evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Input required name="evidenceReference" aria-label={`Deployment evidence for ${release.release_reference}`} placeholder="Production deployment URL/ID" /><Textarea name="notes" aria-label={`Deployment notes for ${release.release_reference}`} placeholder="Production smoke-test evidence" /><div className="md:col-span-2"><Button type="submit">Record completed production deployment</Button></div></form>}
      {data.canManage && ["awaiting_approval","approved"].includes(release.status) && <form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "cancel", id: release.id, notes: form.get("notes") }); }}><Input required minLength={10} name="notes" aria-label={`Cancellation reason for ${release.release_reference}`} placeholder="Cancellation reason (10+ characters)" /><Button type="submit" variant="secondary">Cancel candidate</Button></form>}
      <div className="mt-4 border-t border-brand-100 pt-3"><p className="text-sm font-bold">Append-only history</p>{data.events.filter((event) => event.release_id === release.id).map((event) => <p key={event.id} className="mt-2 text-xs text-brand-500">{event.event_type.replaceAll("_", " ")} · {new Date(event.performed_at).toLocaleString()} · {event.evidence_reference || event.notes}</p>)}</div>
    </Card>) : <Card><p className="text-sm text-brand-600">No production release candidate has been frozen.</p></Card>}</div>
  </div>;
}
