"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Accessibility, RefreshCw } from "lucide-react";
import { Button, Card, Input, Select, Textarea } from "@/components/ui";

type Run = { id: string; status: string; release_reference: string; application_version: string; started_at: string };
type Result = { id: string; run_id: string; case_key: string; status: string; evidence_reference: string; notes: string };
type QualityCase = { case_key: string; label: string; description: string; category: string; verification_mode: string; critical: boolean };
type Payload = { runs: Run[]; results: Result[]; cases: QualityCase[]; canManage: boolean };

export function PlatformQualityVerification() {
  const [data, setData] = useState<Payload | null>(null); const [runId, setRunId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/platform/quality", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); setRunId((current) => current || result.runs?.[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load quality evidence."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(body: Record<string, unknown>) { setBusy(true); setError(""); setMessage(""); const response = await fetch("/api/platform/quality", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(result.error ?? "Unable to update quality evidence."); return; } if (result.runId) setRunId(result.runId); setMessage(body.action === "finalize" ? `Quality verification finalized as ${result.status}.` : "Quality evidence saved."); await load(); }
  if (!data) return <Card><p className="flex items-center gap-2" role="status"><RefreshCw className="h-4 w-4 animate-spin" /> Loading quality verification…</p>{error && <span className="text-red-700"> {error}</span>}</Card>;
  const run = data.runs.find((item) => item.id === runId); const results = run ? data.results.filter((item) => item.run_id === run.id) : []; const byCase = new Map(results.map((item) => [item.case_key, item])); const pending = results.filter((item) => item.status === "pending").length;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Production release evidence</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><Accessibility className="h-7 w-7" /> Accessibility and Critical Paths</h1><p className="mt-2 text-sm text-brand-600">Automated checks support—but never replace—keyboard, assistive-technology, zoom, browser, and mobile review.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Start a production quality run</h2><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "start", releaseReference: form.get("releaseReference"), applicationVersion: form.get("applicationVersion"), notes: form.get("notes") }); }}><Input required name="releaseReference" aria-label="Release reference" placeholder="Release ticket or commit" /><Input required name="applicationVersion" aria-label="Application version" placeholder="Application version or commit SHA" /><Textarea name="notes" className="md:col-span-2" aria-label="Quality run notes" placeholder="Scope, browsers, devices, and approved test accounts; never enter credentials" /><div className="md:col-span-2"><Button disabled={busy} type="submit">Start quality verification</Button></div></form></Card>}
    <Card><div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-64 flex-1"><label htmlFor="quality-run" className="text-sm font-bold">Quality run</label><Select id="quality-run" className="mt-2" value={runId} onChange={(event) => setRunId(event.target.value)}><option value="">No run selected</option>{data.runs.map((item) => <option value={item.id} key={item.id}>{item.release_reference} · {item.application_version} · {item.status}</option>)}</Select></div>{run && <span className="rounded-full bg-brand-100 px-3 py-2 text-sm font-bold capitalize">{run.status.replaceAll("_", " ")} · {pending} pending</span>}</div></Card>
    {run ? <div className="space-y-4">{data.cases.map((item) => { const result = byCase.get(item.case_key); if (!result) return null; return <Card key={item.case_key}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{item.label}</p><p className="mt-1 text-sm text-brand-600">{item.description}</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-brand-500">{item.category.replaceAll("_", " ")} · {item.verification_mode.replaceAll("_", " ")} · {item.critical ? "critical" : "non-critical"}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold capitalize">{result.status}</span></div>{data.canManage && run.status === "in_progress" && <form className="mt-4 grid gap-3 md:grid-cols-[160px_1fr]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "result", id: result.id, status: form.get("status"), evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Select name="status" defaultValue={result.status === "pending" ? "passed" : result.status} aria-label={`${item.label} result`}><option value="passed">Passed</option><option value="failed">Failed</option><option value="blocked">Blocked</option></Select><Input required name="evidenceReference" defaultValue={result.evidence_reference} aria-label={`${item.label} evidence reference`} placeholder="Test report, trace, screenshot, or review reference" /><Textarea name="notes" defaultValue={result.notes} className="md:col-span-2" aria-label={`${item.label} notes`} placeholder="Observed behavior and coverage; never enter credentials or customer data" /><div className="md:col-span-2"><Button disabled={busy} type="submit">Save case evidence</Button></div></form>}</Card>; })}{data.canManage && run.status === "in_progress" && <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Finalize quality run</h2><p className="mt-1 text-sm text-brand-600">Pending cases block finalization. Failed or blocked cases fail both production quality gates.</p></div><Button disabled={busy || pending > 0} type="button" onClick={() => void submit({ action: "finalize", runId: run.id })}>Finalize quality verification</Button></div></Card>}</div> : <Card><p className="text-sm text-brand-500">No production quality run has been recorded. Accessibility and authenticated critical-path gates remain pending.</p></Card>}
  </div>;
}
