"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { GlobeLock, RefreshCw } from "lucide-react";
import { Button, Card, Input, Select, Textarea } from "@/components/ui";

type Domain = { id: string; tenant_id: string; hostname: string; status: string; ssl_status: string; dns_target: string; dns_verified_at: string | null; ssl_verified_at: string | null; failure_reason: string | null; activated_at: string | null };
type Tenant = { id: string; name: string; slug: string; status: string };
type Attempt = { id: string; domain_id: string; check_type: string; status: string; evidence_reference: string; notes: string; performed_at: string };
type Payload = { domains: Domain[]; tenants: Tenant[]; attempts: Attempt[]; canManage: boolean };

export function PlatformCustomDomains() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/platform/domains", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load custom domains."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(body: Record<string, unknown>) { setError(""); setMessage(""); const response = await fetch("/api/platform/domains", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to update domain evidence."); return; } setMessage(body.action === "verify_dns" ? `DNS check completed: ownership ${result.ownershipPassed ? "passed" : "failed"}, routing ${result.routePassed ? "passed" : "failed"}.` : "Domain lifecycle evidence saved."); await load(); }
  if (!data) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading custom domains...</p>{error && <span className="text-red-700"> {error}</span>}</Card>;
  const tenantName = (id: string) => data.tenants.find((tenant) => tenant.id === id)?.name ?? id;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Production operations</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><GlobeLock className="h-7 w-7" /> Custom Domain Operations</h1><p className="mt-2 text-sm text-brand-600">Run live DNS checks, record certificate evidence, activate only verified domains, and preserve an audited rollback path.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}
    {data.domains.length ? data.domains.map((domain) => <Card key={domain.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-display text-xl font-bold">{domain.hostname}</h2><p className="mt-1 text-sm text-brand-600">{tenantName(domain.tenant_id)} · DNS {domain.status.replaceAll("_", " ")} · SSL {domain.ssl_status}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold uppercase">{domain.status}</span></div>
      {domain.failure_reason && <p className="mt-3 text-sm font-semibold text-red-700">{domain.failure_reason}</p>}
      {data.canManage && <div className="mt-4 space-y-4">{domain.status !== "active" && <Button type="button" variant="secondary" onClick={() => void submit({ action: "verify_dns", id: domain.id })}>Run live DNS verification</Button>}
        {(["dns_verified","inactive"].includes(domain.status)) && <form className="grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "ssl", id: domain.id, status: form.get("status"), evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Select name="status" aria-label={`SSL result for ${domain.hostname}`}><option value="passed">SSL passed</option><option value="failed">SSL failed</option></Select><Input required name="evidenceReference" aria-label={`SSL evidence for ${domain.hostname}`} placeholder="Certificate monitor/report reference" /><Textarea name="notes" className="md:col-span-2" aria-label={`SSL notes for ${domain.hostname}`} placeholder="Issuer, SAN, validity, and inspection notes" /><div><Button type="submit">Record SSL evidence</Button></div></form>}
        {domain.status === "dns_verified" && domain.ssl_status === "active" && <form className="flex flex-col gap-3 sm:flex-row" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "activate", id: domain.id, evidenceReference: form.get("evidenceReference") }); }}><Input required name="evidenceReference" aria-label={`Activation evidence for ${domain.hostname}`} placeholder="Activation/change ticket reference" /><Button type="submit">Activate as canonical</Button></form>}
        {domain.status === "active" && <form className="grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "rollback", id: domain.id, evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Input required name="evidenceReference" aria-label={`Rollback evidence for ${domain.hostname}`} placeholder="Incident/change reference" /><Textarea required name="notes" aria-label={`Rollback reason for ${domain.hostname}`} placeholder="Rollback reason and outcome" /><div className="md:col-span-2"><Button type="submit" variant="secondary">Roll back to managed subdomain</Button></div></form>}
      </div>}
      <div className="mt-5 border-t border-brand-100 pt-3"><p className="text-sm font-bold">Append-only evidence</p>{data.attempts.filter((item) => item.domain_id === domain.id).map((item) => <p key={item.id} className="mt-2 text-xs text-brand-500">{item.check_type.replaceAll("_", " ")} · {item.status} · {new Date(item.performed_at).toLocaleString()} · {item.evidence_reference}</p>)}</div>
    </Card>) : <Card><p className="text-sm text-brand-600">No custom-domain requests exist.</p></Card>}
  </div>;
}
