"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { RefreshCw, ShieldAlert } from "lucide-react";
import { Button, Card, Select, Textarea } from "@/components/ui";

type Event = { id: string; tenant_id?: string; correlation_id?: string; event_type: string; severity: string; summary: string; metadata: Record<string, unknown>; status: string; resolution_notes: string; created_at: string };
export function PlatformSecurityEvents() { const [events, setEvents] = useState<Event[]>([]); const [tenants, setTenants] = useState<Record<string,string>>({}); const [canManage, setCanManage] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/platform/security", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setEvents(result.events ?? []); setTenants(result.tenants ?? {}); setCanManage(Boolean(result.canManage)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load security events."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]); async function save(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/platform/security", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: values.get("status"), resolutionNotes: values.get("resolutionNotes") }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to update the event."); return; } await load(); }
  if (loading) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading security events…</p></Card>; return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Platform operations</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><ShieldAlert className="h-7 w-7" /> Security events</h1><p className="mt-2 text-sm text-brand-600">Review privacy-safe abuse signals. These application events supplement—not replace—external monitoring and incident response.</p></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="space-y-4">{events.length ? events.map((item) => <Card key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="font-display text-lg font-bold">{item.summary}</p><p className="mt-1 text-xs text-brand-500">{item.tenant_id ? tenants[item.tenant_id] || item.tenant_id : "Platform"} · {new Date(item.created_at).toLocaleString()}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold capitalize">{item.severity} · {item.status}</span></div><p className="mt-3 text-xs text-brand-500">Type: {item.event_type}{item.correlation_id ? ` · Correlation: ${item.correlation_id}` : ""}</p>{canManage && <form className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto]" onSubmit={(event) => void save(event, item.id)}><Select name="status" defaultValue={item.status === "open" ? "investigating" : item.status} aria-label="Security event status"><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="ignored">Ignored</option></Select><Textarea name="resolutionNotes" defaultValue={item.resolution_notes} aria-label="Security resolution notes" placeholder="Record evidence and the review outcome." /><Button type="submit">Save review</Button></form>}</Card>) : <Card><p className="text-sm text-brand-500">No security events are recorded.</p></Card>}</div></div>; }
