"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card, Input, Select, Textarea } from "@/components/ui";

type Run = { id: string; status: string; tenant_a_id: string; tenant_b_id: string; release_reference: string; notes: string; started_at: string; completed_at?: string };
type Result = { id: string; run_id: string; case_key: string; status: string; evidence_reference: string; evidence: Record<string, unknown>; notes: string; verified_at?: string };
type VerificationCase = { case_key: string; label: string; description: string; verification_mode: "automatic_metadata" | "manual_behavioral"; risk_level: string; sort_order: number };
type Tenant = { id: string; name: string; status: string };
type Payload = { runs: Run[]; results: Result[]; cases: VerificationCase[]; tenants: Tenant[]; canManage: boolean };

export function PlatformIsolationVerification() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [selectedRun, setSelectedRun] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/platform/isolation", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); setSelectedRun((current) => current || result.runs?.[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load isolation verification."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(body: Record<string, unknown>) { setBusy(true); setError(""); setMessage(""); const response = await fetch("/api/platform/isolation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(result.error ?? "Unable to update the verification run."); return; } setMessage(body.action === "finalize" ? `Verification finalized as ${result.status}.` : "Verification evidence saved."); if (result.runId) setSelectedRun(result.runId); await load(); }
  if (!data) return <Card><p className="flex items-center gap-2"><RefreshCw className="h-4 w-4 animate-spin" /> Loading production isolation evidence…</p>{error && <span className="text-red-700"> {error}</span>}</Card>;
  const run = data.runs.find((item) => item.id === selectedRun); const results = run ? data.results.filter((item) => item.run_id === run.id) : []; const byCase = new Map(results.map((item) => [item.case_key, item])); const pending = results.filter((item) => item.status === "pending").length; const tenantName = (id: string) => data.tenants.find((item) => item.id === id)?.name ?? id;
  return <div className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">Production security evidence</p><h1 className="mt-2 flex items-center gap-2 font-display text-3xl font-extrabold"><ShieldCheck className="h-7 w-7" /> RLS and Tenant-Isolation Verification</h1><p className="mt-2 text-sm text-brand-600">Automatic metadata checks do not replace behavioral testing. A run passes only after every production case has recorded evidence.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}
    {data.canManage && <Card><h2 className="font-display text-xl font-bold">Start a production verification run</h2><p className="mt-1 text-sm text-brand-500">Use two approved, non-customer test tenants in production. The harness performs read-only metadata checks and creates pending behavioral cases.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "start", tenantAId: form.get("tenantAId"), tenantBId: form.get("tenantBId"), releaseReference: form.get("releaseReference"), notes: form.get("notes") }); }}><Select required name="tenantAId" aria-label="Tenant A"><option value="">Select Tenant A</option>{data.tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name} ({tenant.status})</option>)}</Select><Select required name="tenantBId" aria-label="Tenant B"><option value="">Select Tenant B</option>{data.tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name} ({tenant.status})</option>)}</Select><Input required name="releaseReference" aria-label="Release reference" placeholder="Release ticket or commit reference" /><Textarea name="notes" aria-label="Verification run notes" placeholder="Scope and approved test accounts; never enter credentials" /><div className="md:col-span-2"><Button disabled={busy || data.tenants.length < 2} type="submit">Start verification</Button></div></form>{data.tenants.length < 2 && <p className="mt-3 text-sm font-semibold text-amber-800">Two distinct production tenants are required.</p>}</Card>}
    <Card><div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-64 flex-1"><label htmlFor="verification-run" className="text-sm font-bold">Verification run</label><Select id="verification-run" className="mt-2" value={selectedRun} onChange={(event) => setSelectedRun(event.target.value)}><option value="">No run selected</option>{data.runs.map((item) => <option key={item.id} value={item.id}>{item.release_reference} · {item.status} · {new Date(item.started_at).toLocaleString()}</option>)}</Select></div>{run && <span className={`rounded-full px-4 py-2 text-sm font-bold capitalize ${run.status === "passed" ? "bg-green-100 text-green-800" : run.status === "failed" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-900"}`}>{run.status.replaceAll("_", " ")} · {pending} pending</span>}</div>{run && <p className="mt-3 text-sm text-brand-600">{tenantName(run.tenant_a_id)} ↔ {tenantName(run.tenant_b_id)} · Production only</p>}</Card>
    {run && <div className="space-y-4">{data.cases.map((item) => { const result = byCase.get(item.case_key); if (!result) return null; const automatic = item.verification_mode === "automatic_metadata"; return <Card key={item.case_key}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{item.label}</p><p className="mt-1 text-sm text-brand-600">{item.description}</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-brand-500">{automatic ? "Automatic database metadata" : "Manual behavioral evidence"} · {item.risk_level}</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-bold capitalize">{result.status}</span></div>{automatic && <div className="mt-4 rounded-xl bg-brand-50 p-3 text-xs text-brand-700"><p>Evidence: {result.evidence_reference || "Not recorded"}</p><pre className="mt-2 overflow-auto whitespace-pre-wrap">{JSON.stringify(result.evidence, null, 2)}</pre></div>}{!automatic && data.canManage && run.status === "in_progress" && <form className="mt-4 grid gap-3 md:grid-cols-[160px_1fr]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ action: "result", id: result.id, status: form.get("status"), evidenceReference: form.get("evidenceReference"), notes: form.get("notes") }); }}><Select name="status" defaultValue={result.status === "pending" ? "passed" : result.status} aria-label={`${item.label} result`}><option value="passed">Passed</option><option value="failed">Failed</option><option value="blocked">Blocked</option></Select><Input required name="evidenceReference" defaultValue={result.evidence_reference} aria-label={`${item.label} evidence reference`} placeholder="Test report, screenshot, trace, or ticket reference" /><Textarea name="notes" defaultValue={result.notes} className="md:col-span-2" aria-label={`${item.label} notes`} placeholder="Accounts/roles exercised and observed result; never enter credentials or customer content" /><div className="md:col-span-2"><Button disabled={busy} type="submit">Save case evidence</Button></div></form>}</Card>; })}{data.canManage && run.status === "in_progress" && <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Finalize run</h2><p className="mt-1 text-sm text-brand-600">Finalization is blocked while any case is pending. Failed or blocked cases make the entire run fail.</p></div><Button disabled={busy || pending > 0} type="button" onClick={() => void submit({ action: "finalize", runId: run.id })}>Finalize verification</Button></div></Card>}</div>}
    {!run && <Card><p className="text-sm text-brand-500">No production isolation verification run has been recorded. This gate remains pending.</p></Card>}
  </div>;
}
