export type Role =
  | "platform_owner"
  | "platform_admin"
  | "tenant_owner"
  | "tenant_admin"
  | "communication_manager"
  | "content_manager"
  | "course_manager"
  | "event_manager"
  | "community_manager"
  | "community_moderator"
  | "analyst"
  | "support_staff"
  | "member"
  | "guest";
