"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Bookmark, BookmarkCheck, FileText, Search, Star } from "lucide-react";
import { Card, Input } from "@/components/ui";
import { EmptyState } from "@/components/feedback/EmptyState";

export type MemberResource = { id: string; title: string; description: string | null; author: string; resource_type: string; cover_image_url: string | null; file_format: string; file_size_bytes: number | null; version_label: string; allow_download: boolean; featured: boolean; bookmarked: boolean };

export function MemberResourceLibrary({ initialResources, tenantSlug }: { initialResources: MemberResource[]; tenantSlug: string }) {
  const [resources, setResources] = useState(initialResources); const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [savedOnly, setSavedOnly] = useState(false); const [error, setError] = useState("");
  const types = useMemo(() => [...new Set(resources.map((resource) => resource.resource_type))].sort(), [resources]);
  const filtered = useMemo(() => resources.filter((resource) => (!query || `${resource.title} ${resource.description ?? ""} ${resource.author}`.toLowerCase().includes(query.toLowerCase())) && (type === "all" || resource.resource_type === type) && (!savedOnly || resource.bookmarked)), [resources, query, type, savedOnly]);
  async function bookmark(resource: MemberResource) { setError(""); const saved = !resource.bookmarked; const response = await fetch("/api/resources/bookmarks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tenantSlug, resourceId: resource.id, saved }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to update saved resources."); else setResources((current) => current.map((item) => item.id === resource.id ? { ...item, bookmarked: result.saved } : item)); }
  return <>{error && <div role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}<div className="mt-8 grid gap-3 md:grid-cols-[1fr_200px_auto]"><label className="relative"><span className="sr-only">Search resources</span><Search className="absolute left-4 top-3.5 h-4 w-4 text-brand-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-11" placeholder="Search resources, authors, and descriptions" /></label><select value={type} onChange={(event) => setType(event.target.value)} aria-label="Filter resource type" className="rounded-xl border border-brand-200 bg-white px-4 py-3 text-sm font-semibold"><option value="all">All types</option>{types.map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</select><label className="flex items-center gap-2 rounded-xl border border-brand-200 bg-white px-4 py-3 text-sm font-bold"><input type="checkbox" checked={savedOnly} onChange={(event) => setSavedOnly(event.target.checked)} /> Saved only</label></div>
    {filtered.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((resource) => <Card key={resource.id} className="flex min-h-72 flex-col"><div className="relative grid aspect-video place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-brand-900 via-accent-700 to-highlight-500 text-white" style={resource.cover_image_url ? { backgroundImage: `linear-gradient(rgb(0 0 0 / .35),rgb(0 0 0 / .35)),url(${resource.cover_image_url})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><FileText className="h-12 w-12" />{resource.featured && <span className="absolute left-3 top-3 inline-flex items-center gap-1 rounded-full bg-highlight-300 px-2 py-1 text-[10px] font-extrabold uppercase text-brand-900"><Star className="h-3 w-3" /> Featured</span>}<button type="button" onClick={() => void bookmark(resource)} aria-label={resource.bookmarked ? `Remove ${resource.title} from saved resources` : `Save ${resource.title}`} className="absolute right-3 top-3 rounded-full bg-white/95 p-2 text-accent-700">{resource.bookmarked ? <BookmarkCheck className="h-4 w-4" /> : <Bookmark className="h-4 w-4" />}</button></div><p className="mt-5 text-xs font-bold uppercase tracking-wide text-accent-700">{resource.resource_type.replace("_", " ")}{resource.file_format ? ` · ${resource.file_format}` : ""}</p><h2 className="mt-2 font-display text-xl font-bold text-brand-900">{resource.title}</h2>{resource.author && <p className="mt-1 text-xs font-semibold text-brand-500">By {resource.author}</p>}{resource.description && <p className="mt-2 line-clamp-3 text-sm leading-6 text-brand-600">{resource.description}</p>}<div className="mt-auto flex items-center justify-between gap-3 pt-5"><span className="text-xs text-brand-500">v{resource.version_label}{resource.file_size_bytes ? ` · ${formatBytes(resource.file_size_bytes)}` : ""}</span><Link href={`/demo/${tenantSlug}/resources/${resource.id}`} className="text-sm font-bold text-accent-700">View details</Link></div></Card>)}</div> : <EmptyState className="mt-10" title={resources.length ? "No resources match these filters." : "No published resources yet."} description={resources.length ? "Clear or change the filters to see other resources." : "Published resources will appear here after the organization adds them. Check back soon."} actionLabel={resources.length ? undefined : "Return Home"} actionHref={resources.length ? undefined : `/demo/${tenantSlug}`} icon={FileText} />}
  </>;
}

function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / 1024 ** 2).toFixed(1)} MB`; }
