"use client";

import { useState } from "react";
import { Bookmark, BookmarkCheck, Download, ExternalLink, FileClock, FileText } from "lucide-react";
import { Button, Card } from "@/components/ui";
import type { MemberResource } from "@/components/tenant/MemberResourceLibrary";

type Version = { id: string; version_label: string; notes: string; url: string; file_format: string; file_size_bytes: number | null; allow_download: boolean; created_at: string };
export function MemberResourceDetail({ initialResource, tenantSlug }: { initialResource: MemberResource & { full_description: string; url: string; versions: Version[] }; tenantSlug: string }) {
  const [resource, setResource] = useState(initialResource); const [error, setError] = useState("");
  async function bookmark() { const saved = !resource.bookmarked; const response = await fetch("/api/resources/bookmarks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tenantSlug, resourceId: resource.id, saved }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to update saved resources."); else setResource((current) => ({ ...current, bookmarked: result.saved })); }
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div><p className="text-xs font-bold uppercase tracking-wide text-accent-700">{resource.resource_type.replace("_", " ")}{resource.file_format ? ` · ${resource.file_format}` : ""}</p><h1 className="mt-3 font-display text-4xl font-extrabold text-brand-900">{resource.title}</h1>{resource.author && <p className="mt-2 font-semibold text-brand-500">By {resource.author}</p>}<p className="mt-6 whitespace-pre-line leading-7 text-brand-700">{resource.full_description || resource.description || "No additional description has been provided."}</p>{error && <p role="alert" className="mt-4 text-sm font-bold text-red-700">{error}</p>}<div className="mt-7 flex flex-wrap gap-3">{resource.allow_download ? <Button href={resource.url}><Download className="h-4 w-4" /> Download current version</Button> : <a href={resource.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-accent-600 px-4 py-2 text-sm font-bold text-white">Open resource <ExternalLink className="h-4 w-4" /></a>}<Button type="button" variant="secondary" onClick={() => void bookmark()}>{resource.bookmarked ? <BookmarkCheck className="h-4 w-4" /> : <Bookmark className="h-4 w-4" />}{resource.bookmarked ? "Saved" : "Save resource"}</Button></div></div><Card><FileText className="h-8 w-8 text-accent-700" /><h2 className="mt-4 font-display text-xl font-bold">Resource details</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold text-brand-500">Current version</dt><dd>v{resource.version_label}</dd></div>{resource.file_size_bytes && <div><dt className="font-bold text-brand-500">File size</dt><dd>{formatBytes(resource.file_size_bytes)}</dd></div>}</dl></Card>{resource.versions.length > 0 && <Card className="lg:col-span-2"><h2 className="flex items-center gap-2 font-display text-xl font-bold"><FileClock className="h-5 w-5 text-accent-700" /> Published versions</h2><div className="mt-4 divide-y">{resource.versions.map((version) => <div key={version.id} className="flex items-center gap-3 py-4"><div className="flex-1"><p className="font-bold">Version {version.version_label}</p><p className="text-xs text-brand-500">{new Date(version.created_at).toLocaleDateString()}{version.file_format ? ` · ${version.file_format}` : ""}{version.file_size_bytes ? ` · ${formatBytes(version.file_size_bytes)}` : ""}</p>{version.notes && <p className="mt-1 text-sm text-brand-600">{version.notes}</p>}</div><a href={version.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-accent-700">{version.allow_download ? "Download" : "Open"}</a></div>)}</div></Card>}</div>;
}
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 ** 2) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / 1024 ** 2).toFixed(1)} MB`; }
