"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Clock3, Download, ExternalLink, MapPin, PlayCircle, Search, Star, Users, Video } from "lucide-react";
import { Button, Card, Input } from "@/components/ui";

type Replay = { id: string; title: string; description: string; url: string; access_level: string; allow_download: boolean };
type MemberEvent = { id: string; title: string; description: string | null; starts_at: string; ends_at: string | null; timezone: string; event_format: string; venue_name: string; venue_address: string; location_url: string | null; cover_image_url: string | null; capacity: number | null; registration_required: boolean; registration_deadline: string | null; waitlist_enabled: boolean; member_instructions: string; featured: boolean; registration_status: string | null; replays: Replay[] };

export function MemberEventsExperience({ initialEvents, tenantSlug }: { initialEvents: MemberEvent[]; tenantSlug: string }) {
  const [events, setEvents] = useState(initialEvents); const [view, setView] = useState<"upcoming" | "past">("upcoming"); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const now = Date.now();
  const filtered = useMemo(() => events.filter((event) => (view === "upcoming" ? new Date(event.starts_at).getTime() >= now : new Date(event.starts_at).getTime() < now) && `${event.title} ${event.description ?? ""} ${event.venue_name}`.toLowerCase().includes(query.toLowerCase())), [events, view, query, now]);
  async function registration(eventId: string, action: "register" | "cancel") { setBusy(eventId); setError(""); try { const response = await fetch("/api/events/registration", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tenantSlug, eventId, action }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to update registration."); setEvents((current) => current.map((event) => event.id === eventId ? { ...event, registration_status: result.status } : event)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update registration."); } finally { setBusy(""); } }
  return <>{error && <div role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}<div className="mt-8 flex flex-col gap-3 md:flex-row"><div className="inline-flex rounded-xl bg-brand-100 p-1">{(["upcoming","past"] as const).map((item) => <button key={item} type="button" onClick={() => setView(item)} className={`rounded-lg px-4 py-2 text-sm font-bold capitalize ${view === item ? "bg-white text-accent-700 shadow-sm" : "text-brand-500"}`}>{item}</button>)}</div><label className="relative max-w-xl flex-1"><span className="sr-only">Search events</span><Search className="absolute left-4 top-3.5 h-4 w-4 text-brand-400" /><Input value={query} onChange={(change) => setQuery(change.target.value)} placeholder="Search events" className="pl-11" /></label></div>
    {filtered.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((event) => { const active = ["registered","attended"].includes(event.registration_status ?? ""); const waitlisted = event.registration_status === "waitlisted"; const deadlinePassed = event.registration_deadline ? new Date(event.registration_deadline).getTime() < now : false; return <Card key={event.id} className="flex min-h-80 flex-col"><div className="relative grid aspect-video place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-brand-900 via-accent-700 to-highlight-500 text-white" style={event.cover_image_url ? { backgroundImage: `linear-gradient(rgb(0 0 0 / .4),rgb(0 0 0 / .4)),url(${event.cover_image_url})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><CalendarDays className="h-12 w-12" />{event.featured && <span className="absolute left-3 top-3 inline-flex items-center gap-1 rounded-full bg-highlight-300 px-2 py-1 text-[10px] font-extrabold uppercase text-brand-900"><Star className="h-3 w-3" /> Featured</span>}<span className="absolute bottom-3 left-4 text-xs font-extrabold uppercase tracking-[.16em]">{event.event_format.replace("_", " ")}</span></div><div className="mt-5 flex items-center gap-2 text-sm font-bold text-accent-700"><CalendarDays className="h-5 w-5" />{formatEventDate(event.starts_at, event.timezone)}</div>{event.ends_at && <p className="mt-1 flex items-center gap-1 text-xs text-brand-500"><Clock3 className="h-3.5 w-3.5" /> Ends {formatEventDate(event.ends_at, event.timezone)}</p>}<h2 className="mt-4 font-display text-2xl font-bold text-brand-900">{event.title}</h2><p className="mt-3 line-clamp-4 text-sm leading-6 text-brand-600">{event.description || "Join this member event."}</p>{event.venue_name && <p className="mt-3 flex items-start gap-2 text-sm text-brand-600"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />{event.venue_name}{event.venue_address ? ` · ${event.venue_address}` : ""}</p>}{event.capacity && <p className="mt-2 flex items-center gap-2 text-xs font-semibold text-brand-500"><Users className="h-4 w-4" /> Capacity {event.capacity}</p>}
      <div className="mt-auto space-y-3 pt-6">{view === "upcoming" && event.registration_required && !active && !waitlisted && <Button type="button" onClick={() => void registration(event.id, "register")} disabled={busy === event.id || deadlinePassed}>{deadlinePassed ? "Registration closed" : event.waitlist_enabled ? "Register or join waitlist" : "Register"}</Button>}{(active || waitlisted) && <div className="flex items-center justify-between gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${waitlisted ? "bg-yellow-100 text-yellow-800" : "bg-green-100 text-green-800"}`}>{event.registration_status}</span>{view === "upcoming" && <button type="button" onClick={() => void registration(event.id, "cancel")} disabled={busy === event.id} className="text-xs font-bold text-red-700">Cancel registration</button>}</div>}{event.member_instructions && (active || !event.registration_required) && <p className="rounded-lg bg-brand-50 p-3 text-sm text-brand-600">{event.member_instructions}</p>}{event.location_url && view === "upcoming" && (active || !event.registration_required) && <a href={event.location_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-accent-600 px-4 py-2 text-sm font-bold text-white"><Video className="h-4 w-4" /> Join event <ExternalLink className="h-4 w-4" /></a>}{view === "past" && event.replays.map((replay) => <a key={replay.id} href={replay.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-lg border border-brand-200 p-3 text-sm text-brand-800"><PlayCircle className="h-5 w-5 text-accent-600" /><span className="flex-1"><span className="block font-bold">{replay.title}</span>{replay.description && <span className="block text-xs text-brand-500">{replay.description}</span>}</span>{replay.allow_download && <Download className="h-4 w-4" />}</a>)}</div></Card>; })}</div> : <p className="mt-10 rounded-xl border border-brand-200 bg-white p-10 text-center text-brand-500">No {view} events matched your search.</p>}
  </>;
}

function formatEventDate(value: string, timeZone: string) { try { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short", timeZone }).format(new Date(value)); } catch { return new Date(value).toLocaleString(); } }
