"use client";

import { FormEvent, useEffect, useState } from "react";
import { Bot, ExternalLink, Loader2, Send, ShieldCheck, UserRound } from "lucide-react";
import { Button, Card, Field, Textarea } from "@/components/ui";

type Citation = { index: number; title: string; url: string; sourceType: string };
type Message = { role: "user" | "assistant"; content: string; citations?: Citation[]; safety?: boolean };
type CoachSettings = { coachName: string; welcomeMessage: string; disclaimerText: string };

export function MemberAiCoach({ tenantSlug }: { tenantSlug: string }) {
  const [settings, setSettings] = useState<CoachSettings | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [conversationId, setConversationId] = useState<string>();
  const [accepted, setAccepted] = useState(false); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { const response = await fetch(`/api/ai/coach?tenantSlug=${encodeURIComponent(tenantSlug)}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load AI Coach."); setSettings(result.settings); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load AI Coach."); } finally { setLoading(false); } })(); }, [tenantSlug]);
  async function ask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const question = String(data.get("question") ?? "").trim(); if (!question) return; setMessages((current) => [...current, { role: "user", content: question }]); setSending(true); setError(""); form.reset(); try { const response = await fetch("/api/ai/coach", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tenantSlug, question, conversationId, disclaimerAccepted: accepted }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "AI Coach could not respond."); setConversationId(result.conversationId); setMessages((current) => [...current, { role: "assistant", content: result.answer, citations: result.citations, safety: result.safetyEscalation }]); } catch (reason) { setError(reason instanceof Error ? reason.message : "AI Coach could not respond."); } finally { setSending(false); } }
  if (loading) return <Card><p className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" /> Loading AI Coach…</p></Card>;
  if (!settings) return <Card><p role="alert" className="text-sm text-red-700">{error || "AI Coach is unavailable."}</p></Card>;
  return <div className="mx-auto max-w-4xl space-y-5"><div className="text-center"><Bot className="mx-auto h-10 w-10 text-accent-700" /><h1 className="mt-3 font-display text-3xl font-extrabold text-brand-900">{settings.coachName}</h1><p className="mt-2 text-brand-600">{settings.welcomeMessage}</p></div>
    {!accepted ? <Card><div className="flex gap-3"><ShieldCheck className="h-6 w-6 shrink-0 text-accent-700" /><div><h2 className="font-display text-lg font-bold">Before you begin</h2><p className="mt-2 text-sm leading-6 text-brand-600">{settings.disclaimerText}</p><label className="mt-4 flex items-start gap-2 text-sm font-semibold"><input type="checkbox" className="mt-1" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /> I understand and want to continue.</label></div></div></Card> : <><div className="space-y-3" aria-live="polite">{messages.length === 0 && <Card><p className="text-center text-sm text-brand-500">Ask about the organization’s approved episodes, courses, lessons, and resources.</p></Card>}{messages.map((message, index) => <div key={index} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}><Card className={`max-w-[85%] ${message.safety ? "border-amber-300 bg-amber-50" : message.role === "user" ? "bg-brand-900 text-white" : ""}`}><div className="flex gap-2">{message.role === "user" ? <UserRound className="h-5 w-5 shrink-0" /> : <Bot className="h-5 w-5 shrink-0 text-accent-700" />}<div><p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p>{message.citations && message.citations.length > 0 && <div className="mt-4 border-t border-brand-200 pt-3"><p className="text-xs font-bold uppercase text-brand-500">Sources</p>{message.citations.map((citation) => <a key={citation.index} href={citation.url} target={citation.url.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="mt-2 flex items-center gap-2 text-sm font-semibold text-accent-700"><span>[{citation.index}]</span>{citation.title}<ExternalLink className="h-3 w-3" /></a>)}</div>}</div></div></Card></div>)}{sending && <p className="flex items-center gap-2 text-sm text-brand-500"><Loader2 className="h-4 w-4 animate-spin" /> {settings.coachName} is reviewing approved sources…</p>}</div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}<Card><form onSubmit={ask} className="space-y-3"><Field label="Your question" htmlFor="coach-question"><Textarea id="coach-question" name="question" maxLength={4000} className="min-h-24" required /></Field><Button type="submit" disabled={sending}><Send className="h-4 w-4" /> Ask {settings.coachName}</Button></form></Card></>}
  </div>;
}
