import { randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { normalizeCustomHostname, validateCustomHostname } from "@/lib/tenant-domains";
import { getActiveTenantWithPermission } from "@/lib/tenant-context";
import { createAdminClient } from "@/lib/supabase/admin";

const schema = z.union([z.object({ action: z.literal("create"), hostname: z.string().trim().min(3).max(253) }), z.object({ action: z.literal("rotate"), id: z.string().uuid() }), z.object({ action: z.literal("deactivate"), id: z.string().uuid() })]);
function challenge(hostname: string) { const token = randomBytes(24).toString("base64url"); return { verification_record_name: `_upnexx-verification.${hostname}`, verification_record_value: `upnexx-verification=${token}` }; }

export async function GET() { const context = await getActiveTenantWithPermission("tenant.domains.manage"); if (!context) return NextResponse.json({ error: "Domain management permission is required." }, { status: 403 }); const admin = createAdminClient(); const [{ data, error }, { data: attempts }] = await Promise.all([admin.from("tenant_domains").select("id,hostname,domain_type,status,is_primary,ssl_status,verification_record_name,verification_record_value,dns_target,dns_verified_at,ssl_verified_at,last_checked_at,failure_reason,canonical_redirect_enabled,activated_at,deactivated_at,created_at,updated_at").eq("tenant_id", context.tenant.id).order("created_at"), admin.from("tenant_domain_verification_attempts").select("id,domain_id,check_type,status,evidence_reference,notes,performed_at").eq("tenant_id", context.tenant.id).order("performed_at", { ascending: false }).limit(100)]); if (error) return NextResponse.json({ error: /schema cache|does not exist/i.test(error.message) ? "Custom-domain migration 0039 is required." : "Unable to load domains." }, { status: 500 }); return NextResponse.json({ tenant: context.tenant, domains: data ?? [], attempts: attempts ?? [], dnsTarget: process.env.CUSTOM_DOMAIN_CNAME_TARGET || "app.upnexx.net" }, { headers: { "Cache-Control": "no-store" } }); }

export async function POST(request: NextRequest) { const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Check the domain request." }, { status: 400 }); const context = await getActiveTenantWithPermission("tenant.domains.manage"); if (!context) return NextResponse.json({ error: "Domain management permission is required." }, { status: 403 }); const admin = createAdminClient(); const input = parsed.data; const now = new Date().toISOString();
  if (input.action === "create") { const hostname = normalizeCustomHostname(input.hostname); const validation = validateCustomHostname(hostname); if (validation) return NextResponse.json({ error: validation }, { status: 400 }); const record = challenge(hostname); const { data, error } = await admin.from("tenant_domains").insert({ tenant_id: context.tenant.id, hostname, domain_type: "custom", status: "pending", ssl_status: "pending", is_primary: false, dns_target: process.env.CUSTOM_DOMAIN_CNAME_TARGET || "app.upnexx.net", ...record, created_by: context.user.id, updated_by: context.user.id }).select("id").single(); if (error) return NextResponse.json({ error: /unique/i.test(error.message) ? "That hostname is already registered." : "Unable to create the domain request." }, { status: 500 }); await admin.from("audit_logs").insert({ tenant_id: context.tenant.id, user_id: context.user.id, action: "tenant.domain.requested", entity_type: "tenant_domain", entity_id: data.id, metadata: { hostname } }); return NextResponse.json({ created: true }); }
  const { data: domain } = await admin.from("tenant_domains").select("id,hostname,status").eq("id", input.id).eq("tenant_id", context.tenant.id).eq("domain_type", "custom").maybeSingle(); if (!domain) return NextResponse.json({ error: "Custom domain not found." }, { status: 404 });
  if (input.action === "rotate") { if (!["pending","failed","inactive"].includes(domain.status)) return NextResponse.json({ error: "Active or verified domains cannot rotate ownership challenges." }, { status: 409 }); const { error } = await admin.from("tenant_domains").update({ ...challenge(domain.hostname), status: "pending", verified_at: null, dns_verified_at: null, ssl_status: "pending", ssl_verified_at: null, failure_reason: "", last_checked_at: null, updated_by: context.user.id, updated_at: now }).eq("id", domain.id); if (error) return NextResponse.json({ error: "Unable to rotate the domain challenge." }, { status: 500 }); await admin.from("audit_logs").insert({ tenant_id: context.tenant.id, user_id: context.user.id, action: "tenant.domain.challenge_rotated", entity_type: "tenant_domain", entity_id: domain.id, metadata: {} }); return NextResponse.json({ saved: true }); }
  if (domain.status === "active") return NextResponse.json({ error: "Active domains require an evidence-backed platform rollback." }, { status: 409 });
  const { error } = await admin.from("tenant_domains").update({ status: "inactive", is_primary: false, canonical_redirect_enabled: false, updated_by: context.user.id, updated_at: now }).eq("id", domain.id); if (error) return NextResponse.json({ error: "Unable to deactivate the domain." }, { status: 500 }); await admin.from("audit_logs").insert({ tenant_id: context.tenant.id, user_id: context.user.id, action: "tenant.domain.deactivated", entity_type: "tenant_domain", entity_id: domain.id, metadata: {} }); return NextResponse.json({ saved: true });
}
